OPERATOR_MAP = {
    '+': 'plus',
    '-': 'minus',
    '*': 'times',
    '/': 'divided by',
    '=': 'equal to',
    '^': 'to the power of',
    '//': 'integer division by',
    '(': 'open parentheses',
    ')': 'close parentheses',
    '%': 'percent',
    '{': 'open braces',
    '}': 'close braces',
    '[': 'open bracket',
    ']': 'close bracket',
}

CURRENCY_MAP = {
    '$': 'dollar',
    '€': 'euro',
    '£': 'pound',
    '¥': 'yen',
    '₹': 'rupee',
    '₽': 'ruble',
    '₩': 'won',
    '₪': 'shekel',
    '฿': 'baht',
    '₫': 'dong',
    '₱': 'peso',
    '₴': 'hryvnia',
    '₦': 'naira',
    '₲': 'guarani',
    '₵': 'cedi',
    '₡': 'colón',
    '₮': 'tögrög',
    '₸': 'tenge',
    '₺': 'lira',
    '₼': 'manat',
    '₾': 'lari',
    '₿': 'bitcoin',
}

ALTERNATIVE_CURRENCIES = {
    'dollar': '$',
    'usd': '$',
    'euro': '€',
    'eur': '€',
    'pound': '£',
    'gbp': '£',
    'yen': '¥',
    'jpy': '¥',
    'rupee': '₹',
    'inr': '₹',
    'ruble': '₽',
    'rub': '₽',
    'won': '₩',
    'krw': '₩',
    'shekel': '₪',
    'ils': '₪',
    'baht': '฿',
    'thb': '฿',
    'dong': '₫',
    'vnd': '₫',
    'peso': '₱',
    'php': '₱',
    'hryvnia': '₴',
    'uah': '₴',
    'naira': '₦',
    'ngn': '₦',
    'cedi': '₵',
    'ghs': '₵',
    'colón': '₡',
    'crc': '₡',
    'tögrög': '₮',
    'mnt': '₮',
    'tenge': '₸',
    'kzt': '₸',
    'lira': '₺',
    'try': '₺',
    'manat': '₼',
    'azn': '₼',
    'lari': '₾',
    'gel': '₾',
    'bitcoin': '₿',
    'btc': '₿',
}

MINOR_CURRENCY_MAP = {
    'dollar': 'cent',
    'euro': 'cent',
    'pound': 'penny',
    'yen': 'sen',
    'rupee': 'paisa',
    'ruble': 'kopeck',
    'won': 'jeon',
    'shekel': 'agora',
    'baht': 'satang',
    'dong': 'hao',
    'peso': 'centavo',
    'hryvnia': 'kopiyka',
    'naira': 'kobo',
    'cedi': 'pesewa',
    'colón': 'céntimo',
    'tögrög': 'möngö',
    'tenge': 'tiyn',
    'lira': 'kuruş',
    'manat': 'qəpik',
    'lari': 'tetri',
    'bitcoin': 'satoshi',
}
