# coding: utf-8

"""
    Antimatter Security Lakehouse Public API

    Interact with the Antimatter ASL API

    The version of the OpenAPI document: 0.0.2
    Contact: support@antimatter.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asl_api.api.content_v1alpha1_api import ContentV1alpha1Api


class TestContentV1alpha1Api(unittest.TestCase):
    """ContentV1alpha1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = ContentV1alpha1Api()

    def tearDown(self) -> None:
        pass

    def test_content_v1_alpha1_get_mitre_enterprise(self) -> None:
        """Test case for content_v1_alpha1_get_mitre_enterprise

        """
        pass

    def test_content_v1_alpha1_get_mitre_enterprise_details(self) -> None:
        """Test case for content_v1_alpha1_get_mitre_enterprise_details

        """
        pass

    def test_content_v1_alpha1_get_preset_data_sources(self) -> None:
        """Test case for content_v1_alpha1_get_preset_data_sources

        """
        pass

    def test_content_v1_alpha1_get_preset_gold(self) -> None:
        """Test case for content_v1_alpha1_get_preset_gold

        """
        pass

    def test_content_v1_alpha1_get_preset_gold_list(self) -> None:
        """Test case for content_v1_alpha1_get_preset_gold_list

        """
        pass

    def test_content_v1_alpha1_get_preset_pre_transform(self) -> None:
        """Test case for content_v1_alpha1_get_preset_pre_transform

        """
        pass

    def test_content_v1_alpha1_get_preset_pre_transform_list(self) -> None:
        """Test case for content_v1_alpha1_get_preset_pre_transform_list

        """
        pass

    def test_content_v1_alpha1_get_preset_silver(self) -> None:
        """Test case for content_v1_alpha1_get_preset_silver

        """
        pass

    def test_content_v1_alpha1_get_preset_silver_list(self) -> None:
        """Test case for content_v1_alpha1_get_preset_silver_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
