"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
import typing

try:
    import yandex.cloud.priv.datasphere.v2.jobs.admin_project_job_service_pb2
except ImportError:
    import datasphere.yandex.cloud.priv.datasphere.v2.jobs.admin_project_job_service_pb2


_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class AdminProjectJobServiceStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    DownloadJobSystemLogs: grpc.UnaryUnaryMultiCallable[
        yandex.cloud.priv.datasphere.v2.jobs.admin_project_job_service_pb2.DownloadJobSystemLogsRequest,
        yandex.cloud.priv.datasphere.v2.jobs.admin_project_job_service_pb2.DownloadJobSystemLogsResponse,
    ]

class AdminProjectJobServiceAsyncStub:
    DownloadJobSystemLogs: grpc.aio.UnaryUnaryMultiCallable[
        yandex.cloud.priv.datasphere.v2.jobs.admin_project_job_service_pb2.DownloadJobSystemLogsRequest,
        yandex.cloud.priv.datasphere.v2.jobs.admin_project_job_service_pb2.DownloadJobSystemLogsResponse,
    ]

class AdminProjectJobServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def DownloadJobSystemLogs(
        self,
        request: yandex.cloud.priv.datasphere.v2.jobs.admin_project_job_service_pb2.DownloadJobSystemLogsRequest,
        context: _ServicerContext,
    ) -> typing.Union[yandex.cloud.priv.datasphere.v2.jobs.admin_project_job_service_pb2.DownloadJobSystemLogsResponse, collections.abc.Awaitable[yandex.cloud.priv.datasphere.v2.jobs.admin_project_job_service_pb2.DownloadJobSystemLogsResponse]]: ...

def add_AdminProjectJobServiceServicer_to_server(servicer: AdminProjectJobServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
