from .lib_logger import *
from _typeshed import Incomplete

logger: Incomplete

class CArgParserCommon:
    __inst__: Incomplete
    __arg_info__: Incomplete
    def __init__(self, name: str, desc: str = 'No Description.', sign_log: str = 'No Sign') -> None: ...
    def get_parser_instance(self): ...
    def get_info_handler(self): ...
    def extract_arg_info(self): ...
    def get_arg_info(self, item_name) -> None: ...
    def post_proc_of_parse(self, arg_info) -> None: ...

class CHargs:
    __cmd__: Incomplete
    __arg_leng__: Incomplete
    __arg_parser__: Incomplete
    def __init__(self, class_inst: CArgParserCommon) -> None: ...
    def get_cmd(self): ...
    def get_arg_leng(self): ...
    def get_arg_data(self, item_name): ...
