from units.quantity import Quantity

class AbstractUnit(object):
    def __init__(self, is_si: bool) -> None: ...
    def __call__(self, quantity: Quantity | float | int) -> Quantity: ...
    def canonical(self) -> Quantity: ...
    def invert(self) -> Quantity: ...
    def is_si(self) -> bool: ...
    def squeeze(self) -> Quantity: ...
    def str_includes_multiplier(self) -> bool: ...
