from units.abstract import AbstractUnit
from units.quantity import Quantity

def compatible(unit1: AbstractUnit, unit2: AbstractUnit) -> bool: ...
def within_epsilon(quantity1: Quantity, quantity2: Quantity) -> bool: ...
