"""SI units can take PREFIXES which imply a multiplier. The si module
encodes logic to handle these PREFIXES and create SI units."""

from typing import Dict

PREFIXES: Dict[str, float]

def prefixed(unit_str: str) -> bool: ...
def multiplier(unit_str: str) -> float: ...
def without_prefix(unit_str: str) -> str: ...
def can_make(unit_str: str) -> bool: ...
