"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
import typing

try:
    import yandex.cloud.priv.iam.v1.inner.service_registry_pb2
except ImportError:
    import datasphere.yandex.cloud.priv.iam.v1.inner.service_registry_pb2


try:
    import yandex.cloud.priv.iam.v1.inner.service_registry_service_pb2
except ImportError:
    import datasphere.yandex.cloud.priv.iam.v1.inner.service_registry_service_pb2


try:
    import yandex.cloud.priv.operation.operation_pb2
except ImportError:
    import datasphere.yandex.cloud.priv.operation.operation_pb2


_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class ServiceRegistryServiceStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    Get: grpc.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.inner.service_registry_service_pb2.GetServiceRequest,
        yandex.cloud.priv.iam.v1.inner.service_registry_pb2.Service,
    ]

    ListServicesWithVersions: grpc.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.inner.service_registry_service_pb2.ListServicesWithVersionsRequest,
        yandex.cloud.priv.iam.v1.inner.service_registry_service_pb2.ListServicesWithVersionsResponse,
    ]

    Create: grpc.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.inner.service_registry_service_pb2.CreateServiceRequest,
        yandex.cloud.priv.operation.operation_pb2.Operation,
    ]

    Update: grpc.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.inner.service_registry_service_pb2.UpdateServiceRequest,
        yandex.cloud.priv.operation.operation_pb2.Operation,
    ]

    Delete: grpc.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.inner.service_registry_service_pb2.DeleteServiceRequest,
        yandex.cloud.priv.operation.operation_pb2.Operation,
    ]

    GetVersion: grpc.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.inner.service_registry_service_pb2.GetServiceVersionRequest,
        yandex.cloud.priv.iam.v1.inner.service_registry_pb2.ServiceVersion,
    ]

    CreateVersion: grpc.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.inner.service_registry_service_pb2.CreateServiceVersionRequest,
        yandex.cloud.priv.operation.operation_pb2.Operation,
    ]

    DeleteVersion: grpc.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.inner.service_registry_service_pb2.DeleteServiceVersionRequest,
        yandex.cloud.priv.operation.operation_pb2.Operation,
    ]

class ServiceRegistryServiceAsyncStub:
    Get: grpc.aio.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.inner.service_registry_service_pb2.GetServiceRequest,
        yandex.cloud.priv.iam.v1.inner.service_registry_pb2.Service,
    ]

    ListServicesWithVersions: grpc.aio.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.inner.service_registry_service_pb2.ListServicesWithVersionsRequest,
        yandex.cloud.priv.iam.v1.inner.service_registry_service_pb2.ListServicesWithVersionsResponse,
    ]

    Create: grpc.aio.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.inner.service_registry_service_pb2.CreateServiceRequest,
        yandex.cloud.priv.operation.operation_pb2.Operation,
    ]

    Update: grpc.aio.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.inner.service_registry_service_pb2.UpdateServiceRequest,
        yandex.cloud.priv.operation.operation_pb2.Operation,
    ]

    Delete: grpc.aio.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.inner.service_registry_service_pb2.DeleteServiceRequest,
        yandex.cloud.priv.operation.operation_pb2.Operation,
    ]

    GetVersion: grpc.aio.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.inner.service_registry_service_pb2.GetServiceVersionRequest,
        yandex.cloud.priv.iam.v1.inner.service_registry_pb2.ServiceVersion,
    ]

    CreateVersion: grpc.aio.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.inner.service_registry_service_pb2.CreateServiceVersionRequest,
        yandex.cloud.priv.operation.operation_pb2.Operation,
    ]

    DeleteVersion: grpc.aio.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.inner.service_registry_service_pb2.DeleteServiceVersionRequest,
        yandex.cloud.priv.operation.operation_pb2.Operation,
    ]

class ServiceRegistryServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Get(
        self,
        request: yandex.cloud.priv.iam.v1.inner.service_registry_service_pb2.GetServiceRequest,
        context: _ServicerContext,
    ) -> typing.Union[yandex.cloud.priv.iam.v1.inner.service_registry_pb2.Service, collections.abc.Awaitable[yandex.cloud.priv.iam.v1.inner.service_registry_pb2.Service]]: ...

    @abc.abstractmethod
    def ListServicesWithVersions(
        self,
        request: yandex.cloud.priv.iam.v1.inner.service_registry_service_pb2.ListServicesWithVersionsRequest,
        context: _ServicerContext,
    ) -> typing.Union[yandex.cloud.priv.iam.v1.inner.service_registry_service_pb2.ListServicesWithVersionsResponse, collections.abc.Awaitable[yandex.cloud.priv.iam.v1.inner.service_registry_service_pb2.ListServicesWithVersionsResponse]]: ...

    @abc.abstractmethod
    def Create(
        self,
        request: yandex.cloud.priv.iam.v1.inner.service_registry_service_pb2.CreateServiceRequest,
        context: _ServicerContext,
    ) -> typing.Union[yandex.cloud.priv.operation.operation_pb2.Operation, collections.abc.Awaitable[yandex.cloud.priv.operation.operation_pb2.Operation]]: ...

    @abc.abstractmethod
    def Update(
        self,
        request: yandex.cloud.priv.iam.v1.inner.service_registry_service_pb2.UpdateServiceRequest,
        context: _ServicerContext,
    ) -> typing.Union[yandex.cloud.priv.operation.operation_pb2.Operation, collections.abc.Awaitable[yandex.cloud.priv.operation.operation_pb2.Operation]]: ...

    @abc.abstractmethod
    def Delete(
        self,
        request: yandex.cloud.priv.iam.v1.inner.service_registry_service_pb2.DeleteServiceRequest,
        context: _ServicerContext,
    ) -> typing.Union[yandex.cloud.priv.operation.operation_pb2.Operation, collections.abc.Awaitable[yandex.cloud.priv.operation.operation_pb2.Operation]]: ...

    @abc.abstractmethod
    def GetVersion(
        self,
        request: yandex.cloud.priv.iam.v1.inner.service_registry_service_pb2.GetServiceVersionRequest,
        context: _ServicerContext,
    ) -> typing.Union[yandex.cloud.priv.iam.v1.inner.service_registry_pb2.ServiceVersion, collections.abc.Awaitable[yandex.cloud.priv.iam.v1.inner.service_registry_pb2.ServiceVersion]]: ...

    @abc.abstractmethod
    def CreateVersion(
        self,
        request: yandex.cloud.priv.iam.v1.inner.service_registry_service_pb2.CreateServiceVersionRequest,
        context: _ServicerContext,
    ) -> typing.Union[yandex.cloud.priv.operation.operation_pb2.Operation, collections.abc.Awaitable[yandex.cloud.priv.operation.operation_pb2.Operation]]: ...

    @abc.abstractmethod
    def DeleteVersion(
        self,
        request: yandex.cloud.priv.iam.v1.inner.service_registry_service_pb2.DeleteServiceVersionRequest,
        context: _ServicerContext,
    ) -> typing.Union[yandex.cloud.priv.operation.operation_pb2.Operation, collections.abc.Awaitable[yandex.cloud.priv.operation.operation_pb2.Operation]]: ...

def add_ServiceRegistryServiceServicer_to_server(servicer: ServiceRegistryServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
