"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing

try:
    import yandex.cloud.priv.datasphere.v2.community_pb2
except ImportError:
    import datasphere.yandex.cloud.priv.datasphere.v2.community_pb2


DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class CommunityAuthModel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    FOLDERID_FIELD_NUMBER: builtins.int
    CLOUDID_FIELD_NUMBER: builtins.int
    ORGANIZATIONID_FIELD_NUMBER: builtins.int
    id: builtins.str
    status: yandex.cloud.priv.datasphere.v2.community_pb2.Community.Status.ValueType
    folderId: builtins.str
    cloudId: builtins.str
    organizationId: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        status: yandex.cloud.priv.datasphere.v2.community_pb2.Community.Status.ValueType = ...,
        folderId: builtins.str = ...,
        cloudId: builtins.str = ...,
        organizationId: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cloudId", b"cloudId", "folderId", b"folderId", "id", b"id", "organizationId", b"organizationId", "status", b"status"]) -> None: ...

global___CommunityAuthModel = CommunityAuthModel

@typing.final
class CommunityFullInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class LabelsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    ID_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    LABELS_FIELD_NUMBER: builtins.int
    CREATED_BY_ID_FIELD_NUMBER: builtins.int
    ACCESS_TYPE_FIELD_NUMBER: builtins.int
    CHANNEL_FIELD_NUMBER: builtins.int
    ORGANIZATION_ID_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    BILLING_ACCOUNT_ID_FIELD_NUMBER: builtins.int
    CLOUD_ID_FIELD_NUMBER: builtins.int
    FOLDER_ID_FIELD_NUMBER: builtins.int
    PROJECT_LIMIT_FIELD_NUMBER: builtins.int
    IS_LEGACY_FIELD_NUMBER: builtins.int
    INVITE_TOKEN_FIELD_NUMBER: builtins.int
    ZONE_ID_FIELD_NUMBER: builtins.int
    SSA_FIELD_NUMBER: builtins.int
    id: builtins.str
    name: builtins.str
    description: builtins.str
    created_by_id: builtins.str
    access_type: yandex.cloud.priv.datasphere.v2.community_pb2.Community.AccessType.ValueType
    organization_id: builtins.str
    status: yandex.cloud.priv.datasphere.v2.community_pb2.Community.Status.ValueType
    billing_account_id: builtins.str
    cloud_id: builtins.str
    folder_id: builtins.str
    project_limit: builtins.int
    is_legacy: builtins.bool
    invite_token: builtins.str
    zone_id: builtins.str
    ssa: builtins.str
    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def labels(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    @property
    def channel(self) -> yandex.cloud.priv.datasphere.v2.community_pb2.CommunicationChannel: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        created_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        name: builtins.str = ...,
        description: builtins.str = ...,
        labels: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        created_by_id: builtins.str = ...,
        access_type: yandex.cloud.priv.datasphere.v2.community_pb2.Community.AccessType.ValueType = ...,
        channel: yandex.cloud.priv.datasphere.v2.community_pb2.CommunicationChannel | None = ...,
        organization_id: builtins.str = ...,
        status: yandex.cloud.priv.datasphere.v2.community_pb2.Community.Status.ValueType = ...,
        billing_account_id: builtins.str = ...,
        cloud_id: builtins.str = ...,
        folder_id: builtins.str = ...,
        project_limit: builtins.int = ...,
        is_legacy: builtins.bool = ...,
        invite_token: builtins.str = ...,
        zone_id: builtins.str = ...,
        ssa: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["channel", b"channel", "created_at", b"created_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["access_type", b"access_type", "billing_account_id", b"billing_account_id", "channel", b"channel", "cloud_id", b"cloud_id", "created_at", b"created_at", "created_by_id", b"created_by_id", "description", b"description", "folder_id", b"folder_id", "id", b"id", "invite_token", b"invite_token", "is_legacy", b"is_legacy", "labels", b"labels", "name", b"name", "organization_id", b"organization_id", "project_limit", b"project_limit", "ssa", b"ssa", "status", b"status", "zone_id", b"zone_id"]) -> None: ...

global___CommunityFullInfo = CommunityFullInfo
