"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .integrationresponsedto import (
    IntegrationResponseDto,
    IntegrationResponseDtoTypedDict,
)
from novu_py.types import BaseModel
from typing import Dict, List
from typing_extensions import TypedDict


class IntegrationsControllerListIntegrationsResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: List[IntegrationResponseDtoTypedDict]


class IntegrationsControllerListIntegrationsResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: List[IntegrationResponseDto]
