"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from novu_py.types import BaseModel
from novu_py.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import Dict, List
from typing_extensions import Annotated, TypedDict


class IntegrationsControllerGetWebhookSupportStatusRequestTypedDict(TypedDict):
    provider_or_integration_id: str


class IntegrationsControllerGetWebhookSupportStatusRequest(BaseModel):
    provider_or_integration_id: Annotated[
        str,
        pydantic.Field(alias="providerOrIntegrationId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]


class IntegrationsControllerGetWebhookSupportStatusResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: bool


class IntegrationsControllerGetWebhookSupportStatusResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: bool
