"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .updatesubscriberglobalpreferencesrequestdto import (
    UpdateSubscriberGlobalPreferencesRequestDto,
    UpdateSubscriberGlobalPreferencesRequestDtoTypedDict,
)
from .updatesubscriberpreferenceglobalresponsedto import (
    UpdateSubscriberPreferenceGlobalResponseDto,
    UpdateSubscriberPreferenceGlobalResponseDtoTypedDict,
)
from novu_py.types import BaseModel
from novu_py.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing import Dict, List
from typing_extensions import Annotated, TypedDict


class SubscribersControllerUpdateSubscriberGlobalPreferencesRequestTypedDict(TypedDict):
    subscriber_id: str
    update_subscriber_global_preferences_request_dto: (
        UpdateSubscriberGlobalPreferencesRequestDtoTypedDict
    )


class SubscribersControllerUpdateSubscriberGlobalPreferencesRequest(BaseModel):
    subscriber_id: Annotated[
        str,
        pydantic.Field(alias="subscriberId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    update_subscriber_global_preferences_request_dto: Annotated[
        UpdateSubscriberGlobalPreferencesRequestDto,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class SubscribersControllerUpdateSubscriberGlobalPreferencesResponseTypedDict(
    TypedDict
):
    headers: Dict[str, List[str]]
    result: UpdateSubscriberPreferenceGlobalResponseDtoTypedDict


class SubscribersControllerUpdateSubscriberGlobalPreferencesResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: UpdateSubscriberPreferenceGlobalResponseDto
