
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-16T06:51:49+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "d21c1688b4b8b2589bfa7e0927afa90e64699575",
 "version": "0.0.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
