"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import ansys.api.dbu.v0.dbumodels_pb2
import ansys.api.geometry.v0.unsupported_pb2
import grpc

class UnsupportedStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    SetSoundEnabled: grpc.UnaryUnaryMultiCallable[
        ansys.api.geometry.v0.unsupported_pb2.SoundEnabledRequest,
        ansys.api.dbu.v0.dbumodels_pb2.RequestResult] = ...
    """Turns the beep sound on or off"""


class UnsupportedServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def SetSoundEnabled(self,
        request: ansys.api.geometry.v0.unsupported_pb2.SoundEnabledRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.dbu.v0.dbumodels_pb2.RequestResult:
        """Turns the beep sound on or off"""
        pass


def add_UnsupportedServicer_to_server(servicer: UnsupportedServicer, server: grpc.Server) -> None: ...
