"""Configuration file for the Sphinx documentation builder."""

# This file only contains a selection of the most common options.
# For a full list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup -----------------------------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in anotehr directory, add these directories to sys.path here.
# If the directory is relative to the documentation root, use os.path.abspath to make it absolute, like shown here.

import importlib.metadata as metadata
import os
import sys

sys.path.insert(0, os.path.abspath(".."))

# -- Project information --------------------------------------------------------------------------

project = "iamapackage"
copyright = "MIT License"
author = "Joseph Cobb"
release = metadata.version("iamapackage")

# -- General configuration ------------------------------------------------------------------------

# If your documentation needs a minimal sphinx version, state it here.

# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings.
# They can be extensions coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.doctest",
    "sphinx.ext.todo",
    "sphinx.ext.coverage",
    "sphinx.ext.imgmath",
    "sphinx.ext.viewcode",
    "sphinx.ext.githubpages",
    "sphinx.ext.napoleon",
    "myst_parser",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
# The defaults are to use RST which is fine for this configuration.
source_suffix = [".rst", ".md"]

# THe master toctree document
master_doc = "index"

# The language for content autogenerated by Sphinx.
# Refer to documentation for a list of supported languages

# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" fro mthe command line for these cases.

# List of patterns, relative to source directory, that match files and directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# The name of the Pygments (syntax highlighting) style to use.
# The read-the-doc theme has good defaults with a light color.
# If you want the yellow highlight uncomment the style for sphinx below.
# pygments_style = 'sphinx'

# -- Options for HTML output ----------------------------------------------------------------------

# The theme to use for HTML and HTML Help pages.
# See the documentation for a list of builtin themes.
html_theme = "furo"
html_title = "iamapackage"

# Add any paths that contain custom static files (such as style sheets) here, relative to this directory.
# They are copied after the builtin static files, so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

# Custom sidebar templates, must be a dictionary that maps document names to template names.

# The default sidebars (for documents that don't match any pattern) are defined by theme itself.
# Builtin themes are using these templates by default:
# ``['localtoc.html', 'relations.html', 'sourcelink.html', 'searchbox.html']``

# This is required for the alabaster theme
# refs: http://alabaster.readthedocs/io/en/latest/installation.html#sidebars

# -- Options for HTMLHelp output ------------------------------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "iamapackagedoc"

# -- Options for LaTeX output ---------------------------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper')
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt')
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    # 'preamble': '',
    # LaTeX figure (float) alignment
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files.
# List of tuples (source start file, target name, title, author, documentclass [howto, manual, or own class])
latex_documents = [
    (
        "latex_index",  # this uses a separate section from index.rst
        "iamapackage.tex",
        "iamapackage Documentation",
        "Joseph Cobb",
        "manual",
    )
]

latex_logo = ""

# For "manual" documents, if this is true, then toplevel headings are parts, not chapters.
# latex_use_parts = True

# If true, show page references after internal links.
latex_show_pagerefs = True

# If true, show URL addresses after external links.
# latex_show_urls = False

# Additional stuff for the LaTeX preamble.
# latex_preamble = ''

# Documents to append as an appendix to all manuals.
# latex_appendices = []

# If false, no module index is generated.
latex_domain_indices = False

# -- Options for manual page output ---------------------------------------------------------------

# One entry per manual page.
# List of tuples (source start file, name, description, authors, manual section)
man_pages = [(master_doc, "iamapackage", "iamapackage Documentation", [author], 1)]

# -- Options for Texinfo output -------------------------------------------------------------------

# Grouping the document tree into Texinfo files.
# List of tuples (source start file, target name, title author, dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "iamapackage",
        "iamapackage Documentation",
        author,
        "iamapackage",
        "One line description of project",
        "Miscellaneous",
    )
]

# -- Extension configuration ----------------------------------------------------------------------

# -- Options for todo extension -------------------------------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# -- Options for myst headings --------------------------------------------------------------------
myst_heading_anchors = 3
