from enum import Enum


class AllegementStatus1Code(Enum):
    CANC = "CANC"
    REMO = "REMO"


class AllocationStatus1Code(Enum):
    AOLF = "AOLF"
    AOLP = "AOLP"


class CancellationProcessingStatus1Code(Enum):
    CAND = "CAND"
    CANP = "CANP"
    DEND = "DEND"
    EXCH = "EXCH"
    INTE = "INTE"
    PACK = "PACK"
    PARF = "PARF"
    REJT = "REJT"
    REPR = "REPR"


class CancelledStatusReason12Code(Enum):
    CANI = "CANI"
    CANS = "CANS"
    CSUB = "CSUB"
    CXLR = "CXLR"
    CANT = "CANT"
    CANZ = "CANZ"
    CORP = "CORP"
    SCEX = "SCEX"
    OTHR = "OTHR"
    CANO = "CANO"
    CREG = "CREG"


class CorporateActionEventProcessingStatus1Code(Enum):
    COMP = "COMP"
    PEND = "PEND"
    RECD = "RECD"


class CorporateActionEventStage2Code(Enum):
    PWAL = "PWAL"
    SUAP = "SUAP"
    APPD = "APPD"
    UNAC = "UNAC"
    WHOU = "WHOU"
    CLDE = "CLDE"
    LAPS = "LAPS"


class CorporateActionEventType1Code(Enum):
    DRIP = "DRIP"
    CAPG = "CAPG"
    DVCA = "DVCA"
    DVOP = "DVOP"
    DVSE = "DVSE"
    LIQU = "LIQU"
    MRGR = "MRGR"
    NAME = "NAME"
    SOFF = "SOFF"
    SPLF = "SPLF"
    SPLR = "SPLR"
    TEND = "TEND"
    BONU = "BONU"
    RHDI = "RHDI"
    EXRI = "EXRI"
    CHAN = "CHAN"
    REDO = "REDO"
    EXOP = "EXOP"
    EXOF = "EXOF"
    DECR = "DECR"


class CorporateActionEventType33Code(Enum):
    ACTV = "ACTV"
    ATTI = "ATTI"
    BRUP = "BRUP"
    DFLT = "DFLT"
    BONU = "BONU"
    EXRI = "EXRI"
    CAPD = "CAPD"
    CAPG = "CAPG"
    CAPI = "CAPI"
    DRCA = "DRCA"
    DVCA = "DVCA"
    CHAN = "CHAN"
    COOP = "COOP"
    CLSA = "CLSA"
    CONS = "CONS"
    CONV = "CONV"
    CREV = "CREV"
    DECR = "DECR"
    DETI = "DETI"
    DSCL = "DSCL"
    DVOP = "DVOP"
    DRIP = "DRIP"
    DRAW = "DRAW"
    DTCH = "DTCH"
    EXOF = "EXOF"
    REDM = "REDM"
    MCAL = "MCAL"
    INCR = "INCR"
    PPMT = "PPMT"
    INTR = "INTR"
    RHDI = "RHDI"
    LIQU = "LIQU"
    EXTM = "EXTM"
    MRGR = "MRGR"
    NOOF = "NOOF"
    CERT = "CERT"
    ODLT = "ODLT"
    OTHR = "OTHR"
    PARI = "PARI"
    PCAL = "PCAL"
    PRED = "PRED"
    PINK = "PINK"
    PLAC = "PLAC"
    PDEF = "PDEF"
    PRIO = "PRIO"
    BPUT = "BPUT"
    REDO = "REDO"
    REMK = "REMK"
    BIDS = "BIDS"
    SPLR = "SPLR"
    RHTS = "RHTS"
    DVSC = "DVSC"
    SHPR = "SHPR"
    SMAL = "SMAL"
    SOFF = "SOFF"
    DVSE = "DVSE"
    SPLF = "SPLF"
    TREC = "TREC"
    TEND = "TEND"
    DLST = "DLST"
    SUSP = "SUSP"
    EXWA = "EXWA"
    WTRC = "WTRC"
    WRTH = "WRTH"
    ACCU = "ACCU"
    MTNG = "MTNG"
    INFO = "INFO"
    TNDP = "TNDP"


class CorporateActionOption5Code(Enum):
    CASH = "CASH"
    SECU = "SECU"


class DeniedReason7Code(Enum):
    ADEA = "ADEA"
    DCAL = "DCAL"
    CDCY = "CDCY"
    CDRE = "CDRE"
    CDRG = "CDRG"
    DCAN = "DCAN"
    DPRG = "DPRG"
    DFOR = "DFOR"
    DREP = "DREP"
    DSET = "DSET"
    IPNC = "IPNC"
    LATE = "LATE"
    OTHR = "OTHR"


class FailingReason1Code(Enum):
    AWMO = "AWMO"
    BYIY = "BYIY"
    CLAT = "CLAT"
    ADEA = "ADEA"
    CANR = "CANR"
    CAIS = "CAIS"
    OBJT = "OBJT"
    AWSH = "AWSH"
    PHSE = "PHSE"
    STCD = "STCD"
    DOCY = "DOCY"
    MLAT = "MLAT"
    DOCC = "DOCC"
    BLOC = "BLOC"
    CHAS = "CHAS"
    NEWI = "NEWI"
    CLAC = "CLAC"
    MUNO = "MUNO"
    GLOB = "GLOB"
    PREA = "PREA"
    PART = "PART"
    NOFX = "NOFX"
    CMON = "CMON"
    YCOL = "YCOL"
    COLL = "COLL"
    DEPO = "DEPO"
    FLIM = "FLIM"
    INCA = "INCA"
    LINK = "LINK"
    LACK = "LACK"
    LALO = "LALO"
    MONY = "MONY"
    NCON = "NCON"
    REFS = "REFS"
    SDUT = "SDUT"
    BATC = "BATC"
    CYCL = "CYCL"
    SBLO = "SBLO"
    CPEC = "CPEC"
    MINO = "MINO"
    IAAD = "IAAD"
    OTHR = "OTHR"
    PHCK = "PHCK"
    BENO = "BENO"
    BOTH = "BOTH"
    CLHT = "CLHT"
    DENO = "DENO"
    DISA = "DISA"
    DKNY = "DKNY"
    FROZ = "FROZ"
    LAAW = "LAAW"
    LATE = "LATE"
    LIQU = "LIQU"
    PRCY = "PRCY"
    REGT = "REGT"
    SETS = "SETS"
    CERT = "CERT"
    PRSY = "PRSY"


class InstructionProcessingStatus1Code(Enum):
    CAN1 = "CAN1"
    CAN2 = "CAN2"
    CAN3 = "CAN3"
    CAND = "CAND"
    CANO = "CANO"
    CANP = "CANP"
    CGEN = "CGEN"
    COSE = "COSE"
    CPRC = "CPRC"
    DFLA = "DFLA"
    DONE = "DONE"
    DONF = "DONF"
    EXCH = "EXCH"
    EXSE = "EXSE"
    FORC = "FORC"
    FUTU = "FUTU"
    INTE = "INTE"
    NOTC = "NOTC"
    OPOD = "OPOD"
    OVER = "OVER"
    PACK = "PACK"
    PAFI = "PAFI"
    PART = "PART"
    PPRC = "PPRC"
    REJT = "REJT"
    REPR = "REPR"
    SESE = "SESE"
    STIN = "STIN"
    SUSP = "SUSP"
    TREA = "TREA"
    UNDE = "UNDE"
    MPRC = "MPRC"


class PendingReason7Code(Enum):
    ADEA = "ADEA"
    CONF = "CONF"
    OTHR = "OTHR"
    DQUA = "DQUA"


class PendingReason8Code(Enum):
    AWMO = "AWMO"
    ADEA = "ADEA"
    AUTH = "AUTH"
    CAIS = "CAIS"
    REFU = "REFU"
    AWSH = "AWSH"
    PHSE = "PHSE"
    TAMM = "TAMM"
    DOCY = "DOCY"
    DOCC = "DOCC"
    BLOC = "BLOC"
    CHAS = "CHAS"
    NEWI = "NEWI"
    CLAC = "CLAC"
    MUNO = "MUNO"
    GLOB = "GLOB"
    PREA = "PREA"
    PART = "PART"
    NMAS = "NMAS"
    CMON = "CMON"
    YCOL = "YCOL"
    COLL = "COLL"
    DEPO = "DEPO"
    FLIM = "FLIM"
    NOFX = "NOFX"
    INCA = "INCA"
    LINK = "LINK"
    FUTU = "FUTU"
    LACK = "LACK"
    LALO = "LALO"
    MONY = "MONY"
    NCON = "NCON"
    REFS = "REFS"
    SDUT = "SDUT"
    BATC = "BATC"
    CYCL = "CYCL"
    SBLO = "SBLO"
    CPEC = "CPEC"
    MINO = "MINO"
    IAAD = "IAAD"
    PHCK = "PHCK"
    BENO = "BENO"
    BOTH = "BOTH"
    CLHT = "CLHT"
    DENO = "DENO"
    DISA = "DISA"
    DKNY = "DKNY"
    DQUA = "DQUA"
    FROZ = "FROZ"
    LAAW = "LAAW"
    LATE = "LATE"
    LIQU = "LIQU"
    MCER = "MCER"
    NPAY = "NPAY"
    NSEC = "NSEC"
    PENR = "PENR"
    PRCY = "PRCY"
    REGT = "REGT"
    SETS = "SETS"
    VLDA = "VLDA"
    PRSY = "PRSY"
    CDCY = "CDCY"
    CDRG = "CDRG"
    CONF = "CONF"
    CDRE = "CDRE"
    OTHR = "OTHR"
    IPNC = "IPNC"


class PledgeeType1Code(Enum):
    CPTY = "CPTY"
    REGB = "REGB"


class PriceSource1Code(Enum):
    FUND = "FUND"
    THEO = "THEO"
    VEND = "VEND"


class PriceValueType2Code(Enum):
    DISC = "DISC"
    PREM = "PREM"


class RegistrationProcessingStatus1Code(Enum):
    PACK = "PACK"
    REJT = "REJT"


class RejectionReason69Code(Enum):
    SAFE = "SAFE"
    ADEA = "ADEA"
    LATE = "LATE"
    CAEV = "CAEV"
    DDAT = "DDAT"
    REFE = "REFE"
    OTHR = "OTHR"
    DQUA = "DQUA"
    DSEC = "DSEC"
    INVB = "INVB"
    INVL = "INVL"
    INVN = "INVN"
    MINO = "MINO"
    MUNO = "MUNO"
    VALR = "VALR"


class RejectionReason73Code(Enum):
    SAFE = "SAFE"
    DQUA = "DQUA"
    ADEA = "ADEA"
    DSEC = "DSEC"
    LATE = "LATE"
    CASH = "CASH"
    DDEA = "DDEA"
    DTRD = "DTRD"
    PLCE = "PLCE"
    RTGS = "RTGS"
    NCRR = "NCRR"
    PHYS = "PHYS"
    REFE = "REFE"
    DMON = "DMON"
    MINO = "MINO"
    BATC = "BATC"
    MUNO = "MUNO"
    TXST = "TXST"
    SETS = "SETS"
    IIND = "IIND"
    CAEV = "CAEV"
    CASY = "CASY"
    DDAT = "DDAT"
    SETR = "SETR"
    SDUT = "SDUT"
    INPS = "INPS"
    OTHR = "OTHR"
    ICUS = "ICUS"
    ICAG = "ICAG"
    DEPT = "DEPT"
    IEXE = "IEXE"
    INVB = "INVB"
    INVL = "INVL"
    INVN = "INVN"
    VALR = "VALR"


class RejectionReason76Code(Enum):
    ULNK = "ULNK"
    SAFE = "SAFE"
    DQUA = "DQUA"
    ADEA = "ADEA"
    RTGS = "RTGS"
    NCRR = "NCRR"
    DSEC = "DSEC"
    DADR = "DADR"
    INIR = "INIR"
    CANC = "CANC"
    INTV = "INTV"
    INVA = "INVA"
    REFT = "REFT"
    PHYS = "PHYS"
    REFE = "REFE"
    LACK = "LACK"
    LATE = "LATE"
    NMTY = "NMTY"
    OPNM = "OPNM"
    DMON = "DMON"
    OPTY = "OPTY"
    DCAN = "DCAN"
    DPRG = "DPRG"
    EVNM = "EVNM"
    STAT = "STAT"
    STAM = "STAM"
    SIGN = "SIGN"
    SHAR = "SHAR"
    MINO = "MINO"
    NRGM = "NRGM"
    MLEG = "MLEG"
    BATC = "BATC"
    CADE = "CADE"
    CASH = "CASH"
    DDEA = "DDEA"
    OWNT = "OWNT"
    NRGN = "NRGN"
    MUNO = "MUNO"
    REQW = "REQW"
    TXST = "TXST"
    REPA = "REPA"
    REPO = "REPO"
    REPP = "REPP"
    RREA = "RREA"
    REQM = "REQM"
    RERT = "RERT"
    RSPR = "RSPR"
    SETS = "SETS"
    DTRD = "DTRD"
    IIND = "IIND"
    PLCE = "PLCE"
    INNA = "INNA"
    ICOL = "ICOL"
    BPAR = "BPAR"
    BREF = "BREF"
    BUSE = "BUSE"
    CAEV = "CAEV"
    CASY = "CASY"
    COMC = "COMC"
    CONL = "CONL"
    CPTY = "CPTY"
    DDAT = "DDAT"
    DISC = "DISC"
    DISE = "DISE"
    DORD = "DORD"
    FEEE = "FEEE"
    SETR = "SETR"
    TERM = "TERM"
    VASU = "VASU"
    INPS = "INPS"
    SDUT = "SDUT"
    FORF = "FORF"
    ICUS = "ICUS"
    ICAG = "ICAG"
    DEPT = "DEPT"
    OTHR = "OTHR"
    IEXE = "IEXE"
    INVE = "INVE"
    PLIS = "PLIS"


class RepairReason6Code(Enum):
    BATC = "BATC"
    CAEV = "CAEV"
    CASH = "CASH"
    CASY = "CASY"
    DDAT = "DDAT"
    DDEA = "DDEA"
    DMON = "DMON"
    DQUA = "DQUA"
    DSEC = "DSEC"
    DTRD = "DTRD"
    IIND = "IIND"
    MINO = "MINO"
    MUNO = "MUNO"
    NCRR = "NCRR"
    PHYS = "PHYS"
    PLCE = "PLCE"
    REFE = "REFE"
    RTGS = "RTGS"
    SAFE = "SAFE"
    SETR = "SETR"
    SETS = "SETS"
    TXST = "TXST"
    INPS = "INPS"
    SDUT = "SDUT"
    OTHR = "OTHR"
    IEXE = "IEXE"
    ICAG = "ICAG"
    DEPT = "DEPT"
    ICUS = "ICUS"
    REPA = "REPA"
    CADE = "CADE"
    RERT = "RERT"
    RSPR = "RSPR"
    VASU = "VASU"
    REPO = "REPO"
    REPP = "REPP"
    TERM = "TERM"
    FORF = "FORF"
    ADEA = "ADEA"
    BUSE = "BUSE"
    COMC = "COMC"
    FEEE = "FEEE"
    INNA = "INNA"
    NRGM = "NRGM"
    NRGN = "NRGN"
    ULNK = "ULNK"


class ReplacementProcessingStatus1Code(Enum):
    DEND = "DEND"
    EXCH = "EXCH"
    INTE = "INTE"
    PACK = "PACK"
    PART = "PART"
    PEND = "PEND"
    REJT = "REJT"
    REPL = "REPL"
    REPR = "REPR"


class RepoCallRequestStatus1Code(Enum):
    CACK = "CACK"
    DEND = "DEND"


class ResponseStatus1Code(Enum):
    ACCP = "ACCP"
    ACCT = "ACCT"
    REJT = "REJT"
    SUBR = "SUBR"


class ReversalCode(Enum):
    RVCD = "RVCD"
    RVDB = "RVDB"


class SecuritiesBalanceType11Code(Enum):
    BLOK = "BLOK"
    AWAS = "AWAS"
    AVAI = "AVAI"
    BLCA = "BLCA"
    BLOT = "BLOT"
    BLOV = "BLOV"
    BORR = "BORR"
    COLI = "COLI"
    COLO = "COLO"
    COLA = "COLA"
    LOAN = "LOAN"
    MARG = "MARG"
    PECA = "PECA"
    PEDA = "PEDA"
    PLED = "PLED"
    REGO = "REGO"
    RSTR = "RSTR"
    OTHR = "OTHR"
    TRAN = "TRAN"
    DRAW = "DRAW"
    CLEN = "CLEN"
    DIRT = "DIRT"
    NOMI = "NOMI"
    SPOS = "SPOS"
    UNRG = "UNRG"
    ISSU = "ISSU"
    QUAS = "QUAS"
    LODE = "LODE"


class SecuritiesBalanceType12Code(Enum):
    BLOK = "BLOK"
    AWAS = "AWAS"
    BLCA = "BLCA"
    BLOT = "BLOT"
    BLOV = "BLOV"
    BORR = "BORR"
    BODE = "BODE"
    BORE = "BORE"
    COLI = "COLI"
    COLO = "COLO"
    LOAN = "LOAN"
    LODE = "LODE"
    LORE = "LORE"
    MARG = "MARG"
    PECA = "PECA"
    PEDA = "PEDA"
    PEND = "PEND"
    PENR = "PENR"
    PLED = "PLED"
    REGO = "REGO"
    RSTR = "RSTR"
    OTHR = "OTHR"
    TRAN = "TRAN"
    DRAW = "DRAW"
    WDOC = "WDOC"
    BTRA = "BTRA"


class SecuritiesBalanceType13Code(Enum):
    BLOK = "BLOK"
    AWAS = "AWAS"
    AVAI = "AVAI"
    NOMI = "NOMI"
    PLED = "PLED"
    REGO = "REGO"
    RSTR = "RSTR"
    OTHR = "OTHR"
    SPOS = "SPOS"
    UNRG = "UNRG"
    ISSU = "ISSU"
    QUAS = "QUAS"
    COLA = "COLA"


class SecuritiesBalanceType1Code(Enum):
    BLOK = "BLOK"
    BORR = "BORR"
    COLI = "COLI"
    COLO = "COLO"
    LOAN = "LOAN"
    MARG = "MARG"
    PDMT = "PDMT"
    PRMT = "PRMT"
    PRUM = "PRUM"
    PECA = "PECA"
    PEND = "PEND"
    PENR = "PENR"
    PLED = "PLED"
    PDUM = "PDUM"
    REGO = "REGO"
    RSTR = "RSTR"
    OTHR = "OTHR"
    TRAN = "TRAN"
    DRAW = "DRAW"
    WDOC = "WDOC"
    BTRA = "BTRA"


class SecuritiesBalanceType2Code(Enum):
    CLEN = "CLEN"
    DIRT = "DIRT"
    NOMI = "NOMI"
    OTHR = "OTHR"
    SPOS = "SPOS"
    UNRG = "UNRG"


class SecuritiesBalanceType7Code(Enum):
    COLA = "COLA"
    OTHR = "OTHR"
    CLEN = "CLEN"
    DIRT = "DIRT"
    NOMI = "NOMI"
    SPOS = "SPOS"
    UNRG = "UNRG"
    ISSU = "ISSU"
    QUAS = "QUAS"


class SecuritiesSettlementStatus2Code(Enum):
    PEND = "PEND"
    PENF = "PENF"
    USET = "USET"
    SETT = "SETT"
    PAIN = "PAIN"


class SecuritiesStatementType1Code(Enum):
    CUST = "CUST"
    ACCT = "ACCT"


class SecuritiesTransactionType27Code(Enum):
    BSBK = "BSBK"
    BYIY = "BYIY"
    CNCB = "CNCB"
    COLI = "COLI"
    COLO = "COLO"
    CONV = "CONV"
    FCTA = "FCTA"
    INSP = "INSP"
    ISSU = "ISSU"
    MKDW = "MKDW"
    MKUP = "MKUP"
    NETT = "NETT"
    NSYN = "NSYN"
    OWNE = "OWNE"
    OWNI = "OWNI"
    PAIR = "PAIR"
    PLAC = "PLAC"
    PORT = "PORT"
    REAL = "REAL"
    REDI = "REDI"
    REDM = "REDM"
    RELE = "RELE"
    REPU = "REPU"
    RODE = "RODE"
    RVPO = "RVPO"
    SBBK = "SBBK"
    SBRE = "SBRE"
    SECB = "SECB"
    SECL = "SECL"
    SLRE = "SLRE"
    SUBS = "SUBS"
    SYND = "SYND"
    TBAC = "TBAC"
    TRAD = "TRAD"
    TRPO = "TRPO"
    TRVO = "TRVO"
    TURN = "TURN"
    CLAI = "CLAI"
    CORP = "CORP"
    AUTO = "AUTO"
    SWIF = "SWIF"
    SWIT = "SWIT"
    ETFT = "ETFT"
    REBL = "REBL"
    TRIN = "TRIN"
    TOUT = "TOUT"


class SettlementConditionModificationStatus1Code(Enum):
    PACK = "PACK"
    REJT = "REJT"
    MODP = "MODP"
    DEND = "DEND"
    MODC = "MODC"


class SettlementTransactionCondition4Code(Enum):
    CLEN = "CLEN"
    DIRT = "DIRT"
    DLWM = "DLWM"
    PHYS = "PHYS"
    SPDL = "SPDL"
    SPST = "SPST"
    NOMC = "NOMC"


class StatementBasis1Code(Enum):
    CONT = "CONT"
    SETT = "SETT"
    TRAD = "TRAD"


class StatementBasis2Code(Enum):
    SETT = "SETT"
    TRAD = "TRAD"


class StatementStructure1Code(Enum):
    STAT = "STAT"
    TRAN = "TRAN"


class StatementUpdateTypeCode(Enum):
    COMP = "COMP"
    DELT = "DELT"


class TransactionActivity1Code(Enum):
    BOLE = "BOLE"
    CLAI = "CLAI"
    COLL = "COLL"
    CORP = "CORP"
    SETT = "SETT"


class TransactionStatus1Code(Enum):
    RVSL = "RVSL"
    REBO = "REBO"
    CANC = "CANC"


class TransactionType2Code(Enum):
    REDM = "REDM"
    SUBS = "SUBS"
    SSPL = "SSPL"
    RWPL = "RWPL"
    TRIN = "TRIN"
    TOUT = "TOUT"
    SWII = "SWII"
    SWIO = "SWIO"
    SUAA = "SUAA"
    REAA = "REAA"


class TypeOfPrice11Code(Enum):
    BIDE = "BIDE"
    OFFR = "OFFR"
    NAVL = "NAVL"
    CREA = "CREA"
    CANC = "CANC"
    INTE = "INTE"
    SWNG = "SWNG"
    MIDD = "MIDD"
    RINV = "RINV"
    SWIC = "SWIC"
    MRKT = "MRKT"
    INDC = "INDC"


class TypeOfPrice17Code(Enum):
    BIDE = "BIDE"
    OFFR = "OFFR"
    NAVL = "NAVL"
    CREA = "CREA"
    CANC = "CANC"
    INTE = "INTE"
    SWNG = "SWNG"
    MIDD = "MIDD"
    RINV = "RINV"
    SWIC = "SWIC"
    MRKT = "MRKT"
    INDC = "INDC"
    DDVR = "DDVR"
    ACTU = "ACTU"


class UnmatchedReason12Code(Enum):
    ADEA = "ADEA"
    ACRU = "ACRU"
    IIND = "IIND"
    CPCA = "CPCA"
    CLAT = "CLAT"
    NCRR = "NCRR"
    DDEA = "DDEA"
    DSEC = "DSEC"
    DQUA = "DQUA"
    LEOG = "LEOG"
    LATE = "LATE"
    MIME = "MIME"
    CMIS = "CMIS"
    NMAS = "NMAS"
    DTRA = "DTRA"
    OTHR = "OTHR"
    FRAP = "FRAP"
    PHYS = "PHYS"
    INPS = "INPS"
    PLCE = "PLCE"
    PODU = "PODU"
    DEPT = "DEPT"
    ICAG = "ICAG"
    ICUS = "ICUS"
    IEXE = "IEXE"
    REGD = "REGD"
    RTGS = "RTGS"
    SAFE = "SAFE"
    DMON = "DMON"
    SETS = "SETS"
    SETR = "SETR"
    TXST = "TXST"
    DTRD = "DTRD"
    DELN = "DELN"
    UNBR = "UNBR"
    DDAT = "DDAT"
    DMCT = "DMCT"
    DCMX = "DCMX"


class UnmatchedReason14Code(Enum):
    ADEA = "ADEA"
    ACRU = "ACRU"
    CHAR = "CHAR"
    TERM = "TERM"
    IIND = "IIND"
    CPCA = "CPCA"
    CLAT = "CLAT"
    NCRR = "NCRR"
    DDEA = "DDEA"
    EXEC = "EXEC"
    DSEC = "DSEC"
    DQUA = "DQUA"
    FORF = "FORF"
    LEOG = "LEOG"
    INVE = "INVE"
    LATE = "LATE"
    MCAN = "MCAN"
    MIME = "MIME"
    CMIS = "CMIS"
    NMAS = "NMAS"
    DTRA = "DTRA"
    OTHR = "OTHR"
    FRAP = "FRAP"
    PHYS = "PHYS"
    PLIS = "PLIS"
    INPS = "INPS"
    PLCE = "PLCE"
    PODU = "PODU"
    DEPT = "DEPT"
    ICAG = "ICAG"
    ICUS = "ICUS"
    IEXE = "IEXE"
    REGD = "REGD"
    REPA = "REPA"
    CADE = "CADE"
    REPP = "REPP"
    REPO = "REPO"
    RERT = "RERT"
    RSPR = "RSPR"
    RTGS = "RTGS"
    SAFE = "SAFE"
    DMON = "DMON"
    DDAT = "DDAT"
    SETS = "SETS"
    SETR = "SETR"
    TXST = "TXST"
    DTRD = "DTRD"
    DEAL = "DEAL"
    DELN = "DELN"
    UNBR = "UNBR"
    VASU = "VASU"
    DCMX = "DCMX"
    DMCT = "DMCT"
