# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: divi/proto/core/v1/core.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'divi/proto/core/v1/core.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from divi.proto.core.v1 import health_check_request_pb2 as divi_dot_proto_dot_core_dot_v1_dot_health__check__request__pb2
from divi.proto.core.v1 import health_check_response_pb2 as divi_dot_proto_dot_core_dot_v1_dot_health__check__response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x64ivi/proto/core/v1/core.proto\x12\x07\x63ore.v1\x1a-divi/proto/core/v1/health_check_request.proto\x1a.divi/proto/core/v1/health_check_response.proto2L\n\x04\x43ore\x12\x44\n\x05\x43heck\x12\x1b.core.v1.HealthCheckRequest\x1a\x1c.core.v1.HealthCheckResponse\"\x00\x42\x32Z0github.com/KaikaikaiFang/divine-agent/core/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'divi.proto.core.v1.core_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z0github.com/KaikaikaiFang/divine-agent/core/proto'
  _globals['_CORE']._serialized_start=137
  _globals['_CORE']._serialized_end=213
# @@protoc_insertion_point(module_scope)
