# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings


try:
    from yandex.cloud.priv.ai.platform.v1 import project_pb2 as yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__pb2
except ImportError:
    from datasphere.yandex.cloud.priv.ai.platform.v1 import project_pb2 as yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__pb2


try:
    from yandex.cloud.priv.ai.platform.v1 import project_service_pb2 as yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2
except ImportError:
    from datasphere.yandex.cloud.priv.ai.platform.v1 import project_service_pb2 as yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2


try:
    from yandex.cloud.priv.operation import operation_pb2 as yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2
except ImportError:
    from datasphere.yandex.cloud.priv.operation import operation_pb2 as yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2


GRPC_GENERATED_VERSION = '1.63.2'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in yandex/cloud/priv/ai/platform/v1/project_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ProjectServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/yandex.cloud.priv.ai.platform.v1.ProjectService/Create',
                request_serializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.CreateProjectRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/yandex.cloud.priv.ai.platform.v1.ProjectService/Update',
                request_serializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.UpdateProjectRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/yandex.cloud.priv.ai.platform.v1.ProjectService/Delete',
                request_serializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.DeleteProjectRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.FromString,
                _registered_method=True)
        self.Open = channel.unary_unary(
                '/yandex.cloud.priv.ai.platform.v1.ProjectService/Open',
                request_serializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.OpenProjectRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.FromString,
                _registered_method=True)
        self.ResizeProjectDisk = channel.unary_unary(
                '/yandex.cloud.priv.ai.platform.v1.ProjectService/ResizeProjectDisk',
                request_serializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.ResizeProjectDiskRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/yandex.cloud.priv.ai.platform.v1.ProjectService/Get',
                request_serializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.GetProjectRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__pb2.Project.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/yandex.cloud.priv.ai.platform.v1.ProjectService/List',
                request_serializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.ListProjectsRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.ListProjectsResponse.FromString,
                _registered_method=True)
        self.ListOperations = channel.unary_unary(
                '/yandex.cloud.priv.ai.platform.v1.ProjectService/ListOperations',
                request_serializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.ListProjectOperationsRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.ListProjectOperationsResponse.FromString,
                _registered_method=True)
        self.Export = channel.unary_unary(
                '/yandex.cloud.priv.ai.platform.v1.ProjectService/Export',
                request_serializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.ExportProjectRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.ExportProjectResponse.FromString,
                _registered_method=True)
        self.GetFolderStats = channel.unary_unary(
                '/yandex.cloud.priv.ai.platform.v1.ProjectService/GetFolderStats',
                request_serializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.GetFolderStatsRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.GetFolderStatsResponse.FromString,
                _registered_method=True)
        self.Archive = channel.unary_unary(
                '/yandex.cloud.priv.ai.platform.v1.ProjectService/Archive',
                request_serializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.ArchiveProjectRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.FromString,
                _registered_method=True)
        self.ListServiceAccounts = channel.unary_unary(
                '/yandex.cloud.priv.ai.platform.v1.ProjectService/ListServiceAccounts',
                request_serializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.ListServiceAccountsRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.ListServiceAccountsResponse.FromString,
                _registered_method=True)
        self.ValidateSettings = channel.unary_unary(
                '/yandex.cloud.priv.ai.platform.v1.ProjectService/ValidateSettings',
                request_serializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.ValidateSettingsRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.ValidateSettingsResponse.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/yandex.cloud.priv.ai.platform.v1.ProjectService/Stop',
                request_serializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.StopProjectRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.FromString,
                _registered_method=True)


class ProjectServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Open(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResizeProjectDisk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListOperations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Export(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFolderStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Archive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListServiceAccounts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateSettings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProjectServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.CreateProjectRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.UpdateProjectRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.DeleteProjectRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.SerializeToString,
            ),
            'Open': grpc.unary_unary_rpc_method_handler(
                    servicer.Open,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.OpenProjectRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.SerializeToString,
            ),
            'ResizeProjectDisk': grpc.unary_unary_rpc_method_handler(
                    servicer.ResizeProjectDisk,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.ResizeProjectDiskRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.GetProjectRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__pb2.Project.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.ListProjectsRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.ListProjectsResponse.SerializeToString,
            ),
            'ListOperations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListOperations,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.ListProjectOperationsRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.ListProjectOperationsResponse.SerializeToString,
            ),
            'Export': grpc.unary_unary_rpc_method_handler(
                    servicer.Export,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.ExportProjectRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.ExportProjectResponse.SerializeToString,
            ),
            'GetFolderStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFolderStats,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.GetFolderStatsRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.GetFolderStatsResponse.SerializeToString,
            ),
            'Archive': grpc.unary_unary_rpc_method_handler(
                    servicer.Archive,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.ArchiveProjectRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.SerializeToString,
            ),
            'ListServiceAccounts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListServiceAccounts,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.ListServiceAccountsRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.ListServiceAccountsResponse.SerializeToString,
            ),
            'ValidateSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateSettings,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.ValidateSettingsRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.ValidateSettingsResponse.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.StopProjectRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yandex.cloud.priv.ai.platform.v1.ProjectService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProjectService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yandex.cloud.priv.ai.platform.v1.ProjectService/Create',
            yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.CreateProjectRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yandex.cloud.priv.ai.platform.v1.ProjectService/Update',
            yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.UpdateProjectRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yandex.cloud.priv.ai.platform.v1.ProjectService/Delete',
            yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.DeleteProjectRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Open(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yandex.cloud.priv.ai.platform.v1.ProjectService/Open',
            yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.OpenProjectRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResizeProjectDisk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yandex.cloud.priv.ai.platform.v1.ProjectService/ResizeProjectDisk',
            yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.ResizeProjectDiskRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yandex.cloud.priv.ai.platform.v1.ProjectService/Get',
            yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.GetProjectRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__pb2.Project.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yandex.cloud.priv.ai.platform.v1.ProjectService/List',
            yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.ListProjectsRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.ListProjectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListOperations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yandex.cloud.priv.ai.platform.v1.ProjectService/ListOperations',
            yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.ListProjectOperationsRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.ListProjectOperationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Export(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yandex.cloud.priv.ai.platform.v1.ProjectService/Export',
            yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.ExportProjectRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.ExportProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFolderStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yandex.cloud.priv.ai.platform.v1.ProjectService/GetFolderStats',
            yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.GetFolderStatsRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.GetFolderStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Archive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yandex.cloud.priv.ai.platform.v1.ProjectService/Archive',
            yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.ArchiveProjectRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListServiceAccounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yandex.cloud.priv.ai.platform.v1.ProjectService/ListServiceAccounts',
            yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.ListServiceAccountsRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.ListServiceAccountsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yandex.cloud.priv.ai.platform.v1.ProjectService/ValidateSettings',
            yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.ValidateSettingsRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.ValidateSettingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yandex.cloud.priv.ai.platform.v1.ProjectService/Stop',
            yandex_dot_cloud_dot_priv_dot_ai_dot_platform_dot_v1_dot_project__service__pb2.StopProjectRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
