"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
import typing

try:
    import yandex.cloud.priv.iam.v1.oauth_client_pb2
except ImportError:
    import datasphere.yandex.cloud.priv.iam.v1.oauth_client_pb2


try:
    import yandex.cloud.priv.iam.v1.oauth_client_service_pb2
except ImportError:
    import datasphere.yandex.cloud.priv.iam.v1.oauth_client_service_pb2


try:
    import yandex.cloud.priv.operation.operation_pb2
except ImportError:
    import datasphere.yandex.cloud.priv.operation.operation_pb2


_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class OAuthClientServiceStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    Get: grpc.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.oauth_client_service_pb2.GetOAuthClientRequest,
        yandex.cloud.priv.iam.v1.oauth_client_pb2.OAuthClient,
    ]

    List: grpc.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.oauth_client_service_pb2.ListOAuthClientsRequest,
        yandex.cloud.priv.iam.v1.oauth_client_service_pb2.ListOAuthClientsResponse,
    ]

    Create: grpc.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.oauth_client_service_pb2.CreateOAuthClientRequest,
        yandex.cloud.priv.operation.operation_pb2.Operation,
    ]

    Update: grpc.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.oauth_client_service_pb2.UpdateOAuthClientRequest,
        yandex.cloud.priv.operation.operation_pb2.Operation,
    ]

    Delete: grpc.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.oauth_client_service_pb2.DeleteOAuthClientRequest,
        yandex.cloud.priv.operation.operation_pb2.Operation,
    ]

    Move: grpc.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.oauth_client_service_pb2.MoveOAuthClientRequest,
        yandex.cloud.priv.operation.operation_pb2.Operation,
    ]

class OAuthClientServiceAsyncStub:
    Get: grpc.aio.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.oauth_client_service_pb2.GetOAuthClientRequest,
        yandex.cloud.priv.iam.v1.oauth_client_pb2.OAuthClient,
    ]

    List: grpc.aio.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.oauth_client_service_pb2.ListOAuthClientsRequest,
        yandex.cloud.priv.iam.v1.oauth_client_service_pb2.ListOAuthClientsResponse,
    ]

    Create: grpc.aio.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.oauth_client_service_pb2.CreateOAuthClientRequest,
        yandex.cloud.priv.operation.operation_pb2.Operation,
    ]

    Update: grpc.aio.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.oauth_client_service_pb2.UpdateOAuthClientRequest,
        yandex.cloud.priv.operation.operation_pb2.Operation,
    ]

    Delete: grpc.aio.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.oauth_client_service_pb2.DeleteOAuthClientRequest,
        yandex.cloud.priv.operation.operation_pb2.Operation,
    ]

    Move: grpc.aio.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.oauth_client_service_pb2.MoveOAuthClientRequest,
        yandex.cloud.priv.operation.operation_pb2.Operation,
    ]

class OAuthClientServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Get(
        self,
        request: yandex.cloud.priv.iam.v1.oauth_client_service_pb2.GetOAuthClientRequest,
        context: _ServicerContext,
    ) -> typing.Union[yandex.cloud.priv.iam.v1.oauth_client_pb2.OAuthClient, collections.abc.Awaitable[yandex.cloud.priv.iam.v1.oauth_client_pb2.OAuthClient]]: ...

    @abc.abstractmethod
    def List(
        self,
        request: yandex.cloud.priv.iam.v1.oauth_client_service_pb2.ListOAuthClientsRequest,
        context: _ServicerContext,
    ) -> typing.Union[yandex.cloud.priv.iam.v1.oauth_client_service_pb2.ListOAuthClientsResponse, collections.abc.Awaitable[yandex.cloud.priv.iam.v1.oauth_client_service_pb2.ListOAuthClientsResponse]]: ...

    @abc.abstractmethod
    def Create(
        self,
        request: yandex.cloud.priv.iam.v1.oauth_client_service_pb2.CreateOAuthClientRequest,
        context: _ServicerContext,
    ) -> typing.Union[yandex.cloud.priv.operation.operation_pb2.Operation, collections.abc.Awaitable[yandex.cloud.priv.operation.operation_pb2.Operation]]: ...

    @abc.abstractmethod
    def Update(
        self,
        request: yandex.cloud.priv.iam.v1.oauth_client_service_pb2.UpdateOAuthClientRequest,
        context: _ServicerContext,
    ) -> typing.Union[yandex.cloud.priv.operation.operation_pb2.Operation, collections.abc.Awaitable[yandex.cloud.priv.operation.operation_pb2.Operation]]: ...

    @abc.abstractmethod
    def Delete(
        self,
        request: yandex.cloud.priv.iam.v1.oauth_client_service_pb2.DeleteOAuthClientRequest,
        context: _ServicerContext,
    ) -> typing.Union[yandex.cloud.priv.operation.operation_pb2.Operation, collections.abc.Awaitable[yandex.cloud.priv.operation.operation_pb2.Operation]]: ...

    @abc.abstractmethod
    def Move(
        self,
        request: yandex.cloud.priv.iam.v1.oauth_client_service_pb2.MoveOAuthClientRequest,
        context: _ServicerContext,
    ) -> typing.Union[yandex.cloud.priv.operation.operation_pb2.Operation, collections.abc.Awaitable[yandex.cloud.priv.operation.operation_pb2.Operation]]: ...

def add_OAuthClientServiceServicer_to_server(servicer: OAuthClientServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
