"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.field_mask_pb2
import google.protobuf.internal.containers
import google.protobuf.message
import typing

try:
    import yandex.cloud.priv.access.access_pb2
except ImportError:
    import datasphere.yandex.cloud.priv.access.access_pb2


try:
    import yandex.cloud.priv.iam.v1.resource_type_pb2
except ImportError:
    import datasphere.yandex.cloud.priv.iam.v1.resource_type_pb2


DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class CreateResourceTypeMetadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCE_TYPE_FIELD_NUMBER: builtins.int
    resource_type: builtins.str
    def __init__(
        self,
        *,
        resource_type: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["resource_type", b"resource_type"]) -> None: ...

global___CreateResourceTypeMetadata = CreateResourceTypeMetadata

@typing.final
class UpdateResourceTypeMetadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCE_TYPE_FIELD_NUMBER: builtins.int
    resource_type: builtins.str
    def __init__(
        self,
        *,
        resource_type: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["resource_type", b"resource_type"]) -> None: ...

global___UpdateResourceTypeMetadata = UpdateResourceTypeMetadata

@typing.final
class DeleteResourceTypeMetadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCE_TYPE_FIELD_NUMBER: builtins.int
    resource_type: builtins.str
    def __init__(
        self,
        *,
        resource_type: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["resource_type", b"resource_type"]) -> None: ...

global___DeleteResourceTypeMetadata = DeleteResourceTypeMetadata

@typing.final
class CreateResourceTypeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCE_TYPE_FIELD_NUMBER: builtins.int
    ACCESS_BINDINGS_LISTING_PERMISSION_FIELD_NUMBER: builtins.int
    resource_type: builtins.str
    access_bindings_listing_permission: builtins.str
    def __init__(
        self,
        *,
        resource_type: builtins.str = ...,
        access_bindings_listing_permission: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["access_bindings_listing_permission", b"access_bindings_listing_permission", "resource_type", b"resource_type"]) -> None: ...

global___CreateResourceTypeRequest = CreateResourceTypeRequest

@typing.final
class UpdateResourceTypeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCE_TYPE_FIELD_NUMBER: builtins.int
    UPDATE_MASK_FIELD_NUMBER: builtins.int
    ACCESS_BINDINGS_LISTING_PERMISSION_FIELD_NUMBER: builtins.int
    resource_type: builtins.str
    access_bindings_listing_permission: builtins.str
    @property
    def update_mask(self) -> google.protobuf.field_mask_pb2.FieldMask: ...
    def __init__(
        self,
        *,
        resource_type: builtins.str = ...,
        update_mask: google.protobuf.field_mask_pb2.FieldMask | None = ...,
        access_bindings_listing_permission: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["update_mask", b"update_mask"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["access_bindings_listing_permission", b"access_bindings_listing_permission", "resource_type", b"resource_type", "update_mask", b"update_mask"]) -> None: ...

global___UpdateResourceTypeRequest = UpdateResourceTypeRequest

@typing.final
class DeleteResourceTypeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCE_TYPE_FIELD_NUMBER: builtins.int
    resource_type: builtins.str
    def __init__(
        self,
        *,
        resource_type: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["resource_type", b"resource_type"]) -> None: ...

global___DeleteResourceTypeRequest = DeleteResourceTypeRequest

@typing.final
class GetResourceTypeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCE_TYPE_FIELD_NUMBER: builtins.int
    resource_type: builtins.str
    def __init__(
        self,
        *,
        resource_type: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["resource_type", b"resource_type"]) -> None: ...

global___GetResourceTypeRequest = GetResourceTypeRequest

@typing.final
class ListResourceTypesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    page_size: builtins.int
    page_token: builtins.str
    def __init__(
        self,
        *,
        page_size: builtins.int = ...,
        page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["page_size", b"page_size", "page_token", b"page_token"]) -> None: ...

global___ListResourceTypesRequest = ListResourceTypesRequest

@typing.final
class ListResourceTypeResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCE_TYPES_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    next_page_token: builtins.str
    @property
    def resource_types(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[yandex.cloud.priv.iam.v1.resource_type_pb2.ResourceType]: ...
    def __init__(
        self,
        *,
        resource_types: collections.abc.Iterable[yandex.cloud.priv.iam.v1.resource_type_pb2.ResourceType] | None = ...,
        next_page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["next_page_token", b"next_page_token", "resource_types", b"resource_types"]) -> None: ...

global___ListResourceTypeResponse = ListResourceTypeResponse

@typing.final
class ListResourceTypeAccessBindingsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCE_TYPE_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    resource_type: builtins.str
    page_size: builtins.int
    page_token: builtins.str
    def __init__(
        self,
        *,
        resource_type: builtins.str = ...,
        page_size: builtins.int = ...,
        page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["page_size", b"page_size", "page_token", b"page_token", "resource_type", b"resource_type"]) -> None: ...

global___ListResourceTypeAccessBindingsRequest = ListResourceTypeAccessBindingsRequest

@typing.final
class UpdateResourceTypeAccessBindingsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCE_TYPE_FIELD_NUMBER: builtins.int
    ACCESS_BINDING_DELTAS_FIELD_NUMBER: builtins.int
    resource_type: builtins.str
    @property
    def access_binding_deltas(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[yandex.cloud.priv.access.access_pb2.AccessBindingDelta]: ...
    def __init__(
        self,
        *,
        resource_type: builtins.str = ...,
        access_binding_deltas: collections.abc.Iterable[yandex.cloud.priv.access.access_pb2.AccessBindingDelta] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["access_binding_deltas", b"access_binding_deltas", "resource_type", b"resource_type"]) -> None: ...

global___UpdateResourceTypeAccessBindingsRequest = UpdateResourceTypeAccessBindingsRequest

@typing.final
class UpdateResourceTypeAccessBindingsMetadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCE_TYPE_FIELD_NUMBER: builtins.int
    ACCESS_BINDING_DELTAS_FIELD_NUMBER: builtins.int
    resource_type: builtins.str
    @property
    def access_binding_deltas(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[yandex.cloud.priv.access.access_pb2.AccessBindingDelta]: ...
    def __init__(
        self,
        *,
        resource_type: builtins.str = ...,
        access_binding_deltas: collections.abc.Iterable[yandex.cloud.priv.access.access_pb2.AccessBindingDelta] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["access_binding_deltas", b"access_binding_deltas", "resource_type", b"resource_type"]) -> None: ...

global___UpdateResourceTypeAccessBindingsMetadata = UpdateResourceTypeAccessBindingsMetadata
