"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing

try:
    import yandex.cloud.priv.oauth.claims_pb2
except ImportError:
    import datasphere.yandex.cloud.priv.oauth.claims_pb2


DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ListLoginsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COOKIE_HEADER_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    cookie_header: builtins.str
    """The "Cookie" HTTP-header passed from the end-user's client"""
    page_size: builtins.int
    page_token: builtins.str
    def __init__(
        self,
        *,
        cookie_header: builtins.str = ...,
        page_size: builtins.int = ...,
        page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cookie_header", b"cookie_header", "page_size", b"page_size", "page_token", b"page_token"]) -> None: ...

global___ListLoginsRequest = ListLoginsRequest

@typing.final
class DeviceLogin(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUBJECT_CLAIMS_FIELD_NUMBER: builtins.int
    LAST_SESSION_CREATED_AT_FIELD_NUMBER: builtins.int
    @property
    def subject_claims(self) -> yandex.cloud.priv.oauth.claims_pb2.SubjectClaims:
        """claims of the logged-in subject"""

    @property
    def last_session_created_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """when last time SessionService/Create was successfully completed for the subject"""

    def __init__(
        self,
        *,
        subject_claims: yandex.cloud.priv.oauth.claims_pb2.SubjectClaims | None = ...,
        last_session_created_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["last_session_created_at", b"last_session_created_at", "subject_claims", b"subject_claims"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["last_session_created_at", b"last_session_created_at", "subject_claims", b"subject_claims"]) -> None: ...

global___DeviceLogin = DeviceLogin

@typing.final
class ListLoginsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LOGINS_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    next_page_token: builtins.str
    @property
    def logins(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DeviceLogin]:
        """Fields `sub` & `federation` of nested subject claims are guaranteed to be filled.
        They should be used for building redirects to federation login URLs and login entry deletion requests.
        """

    def __init__(
        self,
        *,
        logins: collections.abc.Iterable[global___DeviceLogin] | None = ...,
        next_page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["logins", b"logins", "next_page_token", b"next_page_token"]) -> None: ...

global___ListLoginsResponse = ListLoginsResponse

@typing.final
class DeleteDeviceLoginRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COOKIE_HEADER_FIELD_NUMBER: builtins.int
    SUBJECT_ID_FIELD_NUMBER: builtins.int
    cookie_header: builtins.str
    """The "Cookie" HTTP header containing the "yc_device" cookie."""
    subject_id: builtins.str
    """Subject identifier (SubjectClaims.sub) of the login history entry to remove."""
    def __init__(
        self,
        *,
        cookie_header: builtins.str = ...,
        subject_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cookie_header", b"cookie_header", "subject_id", b"subject_id"]) -> None: ...

global___DeleteDeviceLoginRequest = DeleteDeviceLoginRequest
