# coding: utf-8

"""
    CDO API

    Use the documentation to explore the endpoints CDO has to offer

    The version of the OpenAPI document: 1.4.0
    Contact: cdo.tac@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdo_sdk_python.api.swagger_redirect_controller_api import SwaggerRedirectControllerApi


class TestSwaggerRedirectControllerApi(unittest.TestCase):
    """SwaggerRedirectControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SwaggerRedirectControllerApi()

    def tearDown(self) -> None:
        pass

    def test_redirect_with_using_redirect_view(self) -> None:
        """Test case for redirect_with_using_redirect_view

        """
        pass


if __name__ == '__main__':
    unittest.main()
