# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

try:
    from yandex.cloud.priv.datasphere.v2.nodedeployer import node_deployer_service_pb2 as yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2
except ImportError:
    from datasphere.yandex.cloud.priv.datasphere.v2.nodedeployer import node_deployer_service_pb2 as yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2


GRPC_GENERATED_VERSION = '1.63.2'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in yandex/cloud/priv/datasphere/v2/nodedeployer/node_deployer_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class NodeDeployerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListGroups = channel.unary_unary(
                '/yandex.cloud.priv.datasphere.v2.nodedeployer.NodeDeployerService/ListGroups',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.ListGroupsResponse.FromString,
                _registered_method=True)
        self.ListNodes = channel.unary_unary(
                '/yandex.cloud.priv.datasphere.v2.nodedeployer.NodeDeployerService/ListNodes',
                request_serializer=yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.ListNodesRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.ListNodesResponse.FromString,
                _registered_method=True)
        self.GetNode = channel.unary_unary(
                '/yandex.cloud.priv.datasphere.v2.nodedeployer.NodeDeployerService/GetNode',
                request_serializer=yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.GetNodeRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.GetNodeResponse.FromString,
                _registered_method=True)
        self.CreateNode = channel.unary_unary(
                '/yandex.cloud.priv.datasphere.v2.nodedeployer.NodeDeployerService/CreateNode',
                request_serializer=yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.CreateNodeRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.CreateNodeResponse.FromString,
                _registered_method=True)
        self.UpdateNode = channel.unary_unary(
                '/yandex.cloud.priv.datasphere.v2.nodedeployer.NodeDeployerService/UpdateNode',
                request_serializer=yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.UpdateNodeRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.UpdateNodeResponse.FromString,
                _registered_method=True)
        self.DeleteNode = channel.unary_unary(
                '/yandex.cloud.priv.datasphere.v2.nodedeployer.NodeDeployerService/DeleteNode',
                request_serializer=yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.DeleteNodeRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SuspendNode = channel.unary_unary(
                '/yandex.cloud.priv.datasphere.v2.nodedeployer.NodeDeployerService/SuspendNode',
                request_serializer=yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.SuspendNodeRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.SuspendNodeResponse.FromString,
                _registered_method=True)
        self.ResumeNode = channel.unary_unary(
                '/yandex.cloud.priv.datasphere.v2.nodedeployer.NodeDeployerService/ResumeNode',
                request_serializer=yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.ResumeNodeRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.ResumeNodeResponse.FromString,
                _registered_method=True)


class NodeDeployerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListGroups(self, request, context):
        """List groups accessible by user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNodes(self, request, context):
        """List nodes on one group
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SuspendNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeDeployerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListGroups': grpc.unary_unary_rpc_method_handler(
                    servicer.ListGroups,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.ListGroupsResponse.SerializeToString,
            ),
            'ListNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNodes,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.ListNodesRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.ListNodesResponse.SerializeToString,
            ),
            'GetNode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNode,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.GetNodeRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.GetNodeResponse.SerializeToString,
            ),
            'CreateNode': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNode,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.CreateNodeRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.CreateNodeResponse.SerializeToString,
            ),
            'UpdateNode': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateNode,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.UpdateNodeRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.UpdateNodeResponse.SerializeToString,
            ),
            'DeleteNode': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteNode,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.DeleteNodeRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SuspendNode': grpc.unary_unary_rpc_method_handler(
                    servicer.SuspendNode,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.SuspendNodeRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.SuspendNodeResponse.SerializeToString,
            ),
            'ResumeNode': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeNode,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.ResumeNodeRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.ResumeNodeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yandex.cloud.priv.datasphere.v2.nodedeployer.NodeDeployerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NodeDeployerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListGroups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yandex.cloud.priv.datasphere.v2.nodedeployer.NodeDeployerService/ListGroups',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.ListGroupsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yandex.cloud.priv.datasphere.v2.nodedeployer.NodeDeployerService/ListNodes',
            yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.ListNodesRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.ListNodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yandex.cloud.priv.datasphere.v2.nodedeployer.NodeDeployerService/GetNode',
            yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.GetNodeRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.GetNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yandex.cloud.priv.datasphere.v2.nodedeployer.NodeDeployerService/CreateNode',
            yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.CreateNodeRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.CreateNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yandex.cloud.priv.datasphere.v2.nodedeployer.NodeDeployerService/UpdateNode',
            yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.UpdateNodeRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.UpdateNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yandex.cloud.priv.datasphere.v2.nodedeployer.NodeDeployerService/DeleteNode',
            yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.DeleteNodeRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SuspendNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yandex.cloud.priv.datasphere.v2.nodedeployer.NodeDeployerService/SuspendNode',
            yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.SuspendNodeRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.SuspendNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yandex.cloud.priv.datasphere.v2.nodedeployer.NodeDeployerService/ResumeNode',
            yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.ResumeNodeRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_nodedeployer_dot_node__deployer__service__pb2.ResumeNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
