"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
import typing

try:
    import yandex.cloud.priv.iam.v1.awscompatibility.delegation_key_service_pb2
except ImportError:
    import datasphere.yandex.cloud.priv.iam.v1.awscompatibility.delegation_key_service_pb2


try:
    import yandex.cloud.priv.operation.operation_pb2
except ImportError:
    import datasphere.yandex.cloud.priv.operation.operation_pb2


_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class DelegationKeyServiceStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    GetKeyIdForSubject: grpc.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.awscompatibility.delegation_key_service_pb2.GetKeyIdForSubjectRequest,
        yandex.cloud.priv.operation.operation_pb2.Operation,
    ]
    """Returns a key id compatible with SignUrl method"""

class DelegationKeyServiceAsyncStub:
    GetKeyIdForSubject: grpc.aio.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.awscompatibility.delegation_key_service_pb2.GetKeyIdForSubjectRequest,
        yandex.cloud.priv.operation.operation_pb2.Operation,
    ]
    """Returns a key id compatible with SignUrl method"""

class DelegationKeyServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def GetKeyIdForSubject(
        self,
        request: yandex.cloud.priv.iam.v1.awscompatibility.delegation_key_service_pb2.GetKeyIdForSubjectRequest,
        context: _ServicerContext,
    ) -> typing.Union[yandex.cloud.priv.operation.operation_pb2.Operation, collections.abc.Awaitable[yandex.cloud.priv.operation.operation_pb2.Operation]]:
        """Returns a key id compatible with SignUrl method"""

def add_DelegationKeyServiceServicer_to_server(servicer: DelegationKeyServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
