# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: nillion/values/v1/service.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Dict,
    Optional,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase


if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


class ValuesStub(betterproto.ServiceStub):
    """A service to interact with values (secrets, public values, etc)."""

    async def store_values(
        self,
        store_store_values_request: "store.StoreValuesRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None,
    ) -> "store.StoreValuesResponse":
        """Store values in the network."""

        return await self._unary_unary(
            "/nillion.values.v1.Values/StoreValues",
            store_store_values_request,
            store.StoreValuesResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def retrieve_values(
        self,
        retrieve_retrieve_values_request: "retrieve.RetrieveValuesRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None,
    ) -> "retrieve.RetrieveValuesResponse":
        """Retrieve values from the network."""

        return await self._unary_unary(
            "/nillion.values.v1.Values/RetrieveValues",
            retrieve_retrieve_values_request,
            retrieve.RetrieveValuesResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def delete_values(
        self,
        delete_delete_values_request: "delete.DeleteValuesRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None,
    ) -> "betterproto_lib_google_protobuf.Empty":
        """Delete values from the network."""

        return await self._unary_unary(
            "/nillion.values.v1.Values/DeleteValues",
            delete_delete_values_request,
            betterproto_lib_google_protobuf.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


import betterproto.lib.google.protobuf as betterproto_lib_google_protobuf

from . import (
    delete,
    retrieve,
    store,
)


class ValuesBase(ServiceBase):
    """A service to interact with values (secrets, public values, etc)."""

    async def store_values(
        self, store_store_values_request: "store.StoreValuesRequest"
    ) -> "store.StoreValuesResponse":
        """Store values in the network."""

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def retrieve_values(
        self, retrieve_retrieve_values_request: "retrieve.RetrieveValuesRequest"
    ) -> "retrieve.RetrieveValuesResponse":
        """Retrieve values from the network."""

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def delete_values(
        self, delete_delete_values_request: "delete.DeleteValuesRequest"
    ) -> "betterproto_lib_google_protobuf.Empty":
        """Delete values from the network."""

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_store_values(
        self,
        stream: "grpclib.server.Stream[store.StoreValuesRequest, store.StoreValuesResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.store_values(request)
        await stream.send_message(response)

    async def __rpc_retrieve_values(
        self,
        stream: "grpclib.server.Stream[retrieve.RetrieveValuesRequest, retrieve.RetrieveValuesResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.retrieve_values(request)
        await stream.send_message(response)

    async def __rpc_delete_values(
        self,
        stream: "grpclib.server.Stream[delete.DeleteValuesRequest, betterproto_lib_google_protobuf.Empty]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.delete_values(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/nillion.values.v1.Values/StoreValues": grpclib.const.Handler(
                self.__rpc_store_values,
                grpclib.const.Cardinality.UNARY_UNARY,
                store.StoreValuesRequest,
                store.StoreValuesResponse,
            ),
            "/nillion.values.v1.Values/RetrieveValues": grpclib.const.Handler(
                self.__rpc_retrieve_values,
                grpclib.const.Cardinality.UNARY_UNARY,
                retrieve.RetrieveValuesRequest,
                retrieve.RetrieveValuesResponse,
            ),
            "/nillion.values.v1.Values/DeleteValues": grpclib.const.Handler(
                self.__rpc_delete_values,
                grpclib.const.Cardinality.UNARY_UNARY,
                delete.DeleteValuesRequest,
                betterproto_lib_google_protobuf.Empty,
            ),
        }
