# coding: utf-8

"""
    Cisco Defense Orchestrator API

    Use the interactive documentation to explore the endpoints CDO has to offer

    The version of the OpenAPI document: 0.0.1
    Contact: cdo.tac@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdo_sdk_python.models.cdo_region_list import CdoRegionList

class TestCdoRegionList(unittest.TestCase):
    """CdoRegionList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CdoRegionList:
        """Test CdoRegionList
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CdoRegionList`
        """
        model = CdoRegionList()
        if include_optional:
            return CdoRegionList(
                items = [
                    cdo_sdk_python.models.cdo_region.CdoRegion(
                        domain = '', 
                        api_domain = '', 
                        description = '', )
                    ]
            )
        else:
            return CdoRegionList(
        )
        """

    def testCdoRegionList(self):
        """Test CdoRegionList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
