from enum import Enum


class AllegementReason1Code(Enum):
    ALG1 = "ALG1"


class AwaitingAffirmationReason1Code(Enum):
    WAFF = "WAFF"


class AwaitingCancellationReason1Code(Enum):
    WCAN = "WCAN"


class RejectionReason78Code(Enum):
    ASTM = "ASTM"
    BUSE = "BUSE"
    CADE = "CADE"
    COMC = "COMC"
    DDAT = "DDAT"
    DDEA = "DDEA"
    DMON = "DMON"
    DQUA = "DQUA"
    DSEC = "DSEC"
    DTRD = "DTRD"
    FEEE = "FEEE"
    FORF = "FORF"
    IEXE = "IEXE"
    IIND = "IIND"
    INNA = "INNA"
    NARR = "NARR"
    NCRR = "NCRR"
    ODNP = "ODNP"
    PLCE = "PLCE"
    QUNP = "QUNP"
    REFE = "REFE"
    CTRA = "CTRA"
    REPO = "REPO"
    REPP = "REPP"
    RERT = "RERT"
    RSPR = "RSPR"
    SAFE = "SAFE"
    SETR = "SETR"
    SETS = "SETS"
    TERM = "TERM"
    TNAR = "TNAR"
    TNIU = "TNIU"
    TQHI = "TQHI"
    TQNP = "TQNP"
    TXST = "TXST"
    ULNK = "ULNK"
    VASU = "VASU"
    INIR = "INIR"
    OPNM = "OPNM"
    OPTY = "OPTY"
    UKWN = "UKWN"
    EXLI = "EXLI"
    INPR = "INPR"
    PRIC = "PRIC"
    EQTY = "EQTY"
    SIDE = "SIDE"
    CADI = "CADI"
    CPTY = "CPTY"
    DISC = "DISC"
    DISE = "DISE"
    RESU = "RESU"
    XRAT = "XRAT"
    ACRU = "ACRU"
    GAMN = "GAMN"
    DFLT = "DFLT"
    FAIL = "FAIL"
    INDT = "INDT"
    OTHR = "OTHR"
    DEPT = "DEPT"
    ICUS = "ICUS"
    ICAG = "ICAG"


class RepairReason7Code(Enum):
    ADEA = "ADEA"
    BATC = "BATC"
    BUSE = "BUSE"
    CADE = "CADE"
    CASH = "CASH"
    CASY = "CASY"
    COMC = "COMC"
    DDAT = "DDAT"
    DDEA = "DDEA"
    DEPT = "DEPT"
    DMON = "DMON"
    DQUA = "DQUA"
    DSEC = "DSEC"
    DTRD = "DTRD"
    FEEE = "FEEE"
    FORF = "FORF"
    ICAG = "ICAG"
    ICUS = "ICUS"
    IEXE = "IEXE"
    IIND = "IIND"
    INNA = "INNA"
    LEOG = "LEOG"
    NARR = "NARR"
    NCRR = "NCRR"
    NRGM = "NRGM"
    NRGN = "NRGN"
    PHYS = "PHYS"
    PLCE = "PLCE"
    CTRA = "CTRA"
    REPO = "REPO"
    REPP = "REPP"
    RERT = "RERT"
    RSPR = "RSPR"
    RTGS = "RTGS"
    SAFE = "SAFE"
    SETR = "SETR"
    SETS = "SETS"
    TERM = "TERM"
    TXST = "TXST"
    ULNK = "ULNK"
    VASU = "VASU"


class UnmatchedReason4Code(Enum):
    ADEA = "ADEA"
    CADE = "CADE"
    CHAR = "CHAR"
    CMIS = "CMIS"
    CPCA = "CPCA"
    DDAT = "DDAT"
    DDEA = "DDEA"
    DEAL = "DEAL"
    DELN = "DELN"
    DEPT = "DEPT"
    DMON = "DMON"
    DQUA = "DQUA"
    DSEC = "DSEC"
    DTRD = "DTRD"
    EXEC = "EXEC"
    FORF = "FORF"
    LATE = "LATE"
    LEOG = "LEOG"
    MCAN = "MCAN"
    NARR = "NARR"
    PHYS = "PHYS"
    PLCE = "PLCE"
    PODU = "PODU"
    REPA = "REPA"
    REPO = "REPO"
    REPP = "REPP"
    RERT = "RERT"
    RSPR = "RSPR"
    RTGS = "RTGS"
    SAFE = "SAFE"
    SETR = "SETR"
    SETS = "SETS"
    TERM = "TERM"
    TXST = "TXST"
    VASU = "VASU"
    POSE = "POSE"
    BORT = "BORT"
    COAX = "COAX"
    OTHI = "OTHI"
    BOFE = "BOFE"
    TACR = "TACR"
    SDAT = "SDAT"
    COID = "COID"
    SCRA = "SCRA"
    ACRU = "ACRU"
    SHAI = "SHAI"
    ACRS = "ACRS"
    DEAS = "DEAS"
    CATI = "CATI"
    TACS = "TACS"
    DBNM = "DBNM"
    MADA = "MADA"
    OLID = "OLID"
    TRSA = "TRSA"
    TRTE = "TRTE"
    BOIA = "BOIA"
    OPLI = "OPLI"
    TRTR = "TRTR"
    LWCO = "LWCO"
    INTT = "INTT"
    CUFC = "CUFC"
    LTME = "LTME"
    ENFC = "ENFC"
    CLSE = "CLSE"
