from enum import Enum


class FinalStatus1Code(Enum):
    STLD = "STLD"
    RJTD = "RJTD"
    CAND = "CAND"
    FNLD = "FNLD"


class PendingFailingSettlement1Code(Enum):
    AWMO = "AWMO"
    AWSH = "AWSH"
    LAAW = "LAAW"
    DOCY = "DOCY"
    CLAT = "CLAT"
    CERT = "CERT"
    MINO = "MINO"
    PHSE = "PHSE"
    SBLO = "SBLO"
    DKNY = "DKNY"
    STCD = "STCD"
    BENO = "BENO"
    LACK = "LACK"
    LATE = "LATE"
    CANR = "CANR"
    MLAT = "MLAT"
    OBJT = "OBJT"
    DOCC = "DOCC"
    BLOC = "BLOC"
    CHAS = "CHAS"
    NEWI = "NEWI"
    CLAC = "CLAC"
    PART = "PART"
    CMON = "CMON"
    COLL = "COLL"
    DEPO = "DEPO"
    FLIM = "FLIM"
    NOFX = "NOFX"
    INCA = "INCA"
    LINK = "LINK"
    BYIY = "BYIY"
    CAIS = "CAIS"
    LALO = "LALO"
    MONY = "MONY"
    NCON = "NCON"
    YCOL = "YCOL"
    REFS = "REFS"
    SDUT = "SDUT"
    CYCL = "CYCL"
    BATC = "BATC"
    GUAD = "GUAD"
    PREA = "PREA"
    GLOB = "GLOB"
    CPEC = "CPEC"
    MUNO = "MUNO"


class PendingSettlement2Code(Enum):
    AWMO = "AWMO"
    CAIS = "CAIS"
    REFU = "REFU"
    AWSH = "AWSH"
    PHSE = "PHSE"
    TAMM = "TAMM"
    DOCY = "DOCY"
    DOCC = "DOCC"
    BLOC = "BLOC"
    CHAS = "CHAS"
    NEWI = "NEWI"
    CLAC = "CLAC"
    MUNO = "MUNO"
    GLOB = "GLOB"
    PREA = "PREA"
    GUAD = "GUAD"
    PART = "PART"
    NMAS = "NMAS"
    CMON = "CMON"
    YCOL = "YCOL"
    COLL = "COLL"
    DEPO = "DEPO"
    FLIM = "FLIM"
    NOFX = "NOFX"
    INCA = "INCA"
    LINK = "LINK"
    FUTU = "FUTU"
    LACK = "LACK"
    LALO = "LALO"
    MONY = "MONY"
    NCON = "NCON"
    REFS = "REFS"
    SDUT = "SDUT"
    BATC = "BATC"
    CYCL = "CYCL"
    SBLO = "SBLO"
    CPEC = "CPEC"
    MINO = "MINO"
    PCAP = "PCAP"


class SuspendedStatusReason1Code(Enum):
    SUBY = "SUBY"
    SUBS = "SUBS"


class UnmatchedStatusReason1Code(Enum):
    CMIS = "CMIS"
    DDAT = "DDAT"
    DELN = "DELN"
    DEPT = "DEPT"
    DMON = "DMON"
    DDEA = "DDEA"
    DQUA = "DQUA"
    CADE = "CADE"
    SETR = "SETR"
    DSEC = "DSEC"
    VASU = "VASU"
    DTRA = "DTRA"
    RSPR = "RSPR"
    REPO = "REPO"
    CLAT = "CLAT"
    RERT = "RERT"
    REPA = "REPA"
    REPP = "REPP"
    PHYS = "PHYS"
    IIND = "IIND"
    FRAP = "FRAP"
    PLCE = "PLCE"
    PODU = "PODU"
    FORF = "FORF"
    REGD = "REGD"
    RTGS = "RTGS"
    ICAG = "ICAG"
    CPCA = "CPCA"
    CHAR = "CHAR"
    IEXE = "IEXE"
    NCRR = "NCRR"
    NMAS = "NMAS"
    SAFE = "SAFE"
    DTRD = "DTRD"
    LATE = "LATE"
    TERM = "TERM"
    ICUS = "ICUS"
