from enum import Enum


class ProcessedStatus7Code(Enum):
    RECE = "RECE"
    SENT = "SENT"
    SNAV = "SNAV"
    WARN = "WARN"
    PACK = "PACK"
    PEND = "PEND"


class RejectionReason80Code(Enum):
    PDAY = "PDAY"
    FAIL = "FAIL"
    GAMN = "GAMN"
    MCER = "MCER"
    DFLT = "DFLT"
    XRAT = "XRAT"
    SECO = "SECO"
    ENDP = "ENDP"
    STAR = "STAR"
    RESU = "RESU"
    NOAC = "NOAC"
    NPAT = "NPAT"
    ELIG = "ELIG"
    BDAY = "BDAY"
    AGID = "AGID"
    DISP = "DISP"
    PERI = "PERI"
    RDTE = "RDTE"
    ACRU = "ACRU"
    VALU = "VALU"
    SECT = "SECT"
    PROR = "PROR"
    BIDI = "BIDI"
    MINP = "MINP"
    MAXP = "MAXP"
    FIRS = "FIRS"
    LAST = "LAST"
    OVPR = "OVPR"
    OVCH = "OVCH"
    OVFL = "OVFL"
    RITR = "RITR"
    SFEE = "SFEE"
    BACK = "BACK"
    COND = "COND"
    MFCF = "MFCF"
    ODLT = "ODLT"
    MPRI = "MPRI"
    PRCH = "PRCH"
    SUPR = "SUPR"
    SUCH = "SUCH"
    UNSP = "UNSP"
    CSRT = "CSRT"
    SERT = "SERT"
    PTYP = "PTYP"
    CINL = "CINL"
    MDIS = "MDIS"
    IDIS = "IDIS"
    FRAC = "FRAC"
    PBAS = "PBAS"
    ROUN = "ROUN"
    ISSR = "ISSR"
    ISSC = "ISSC"


class RejectionReason81Code(Enum):
    FAIL = "FAIL"
    REFI = "REFI"
    DCAN = "DCAN"
    DPRG = "DPRG"
