"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
import typing

try:
    import yandex.cloud.priv.iam.v1.iam_credential_service_pb2
except ImportError:
    import datasphere.yandex.cloud.priv.iam.v1.iam_credential_service_pb2


try:
    import yandex.cloud.priv.iam.v1.revoked_credential_pb2
except ImportError:
    import datasphere.yandex.cloud.priv.iam.v1.revoked_credential_pb2


_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class IamCredentialServiceStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    Revoke: grpc.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.iam_credential_service_pb2.RevokeCredentialRequest,
        yandex.cloud.priv.iam.v1.revoked_credential_pb2.RevokedCredential,
    ]

class IamCredentialServiceAsyncStub:
    Revoke: grpc.aio.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.iam_credential_service_pb2.RevokeCredentialRequest,
        yandex.cloud.priv.iam.v1.revoked_credential_pb2.RevokedCredential,
    ]

class IamCredentialServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Revoke(
        self,
        request: yandex.cloud.priv.iam.v1.iam_credential_service_pb2.RevokeCredentialRequest,
        context: _ServicerContext,
    ) -> typing.Union[yandex.cloud.priv.iam.v1.revoked_credential_pb2.RevokedCredential, collections.abc.Awaitable[yandex.cloud.priv.iam.v1.revoked_credential_pb2.RevokedCredential]]: ...

def add_IamCredentialServiceServicer_to_server(servicer: IamCredentialServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
