# coding: utf-8

"""
    apphub

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from apphub_client.models.apphub_v1_environment_spec_builder_podspec_volumes_inner_flocker import ApphubV1EnvironmentSpecBuilderPodspecVolumesInnerFlocker

class TestApphubV1EnvironmentSpecBuilderPodspecVolumesInnerFlocker(unittest.TestCase):
    """ApphubV1EnvironmentSpecBuilderPodspecVolumesInnerFlocker unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApphubV1EnvironmentSpecBuilderPodspecVolumesInnerFlocker:
        """Test ApphubV1EnvironmentSpecBuilderPodspecVolumesInnerFlocker
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApphubV1EnvironmentSpecBuilderPodspecVolumesInnerFlocker`
        """
        model = ApphubV1EnvironmentSpecBuilderPodspecVolumesInnerFlocker()
        if include_optional:
            return ApphubV1EnvironmentSpecBuilderPodspecVolumesInnerFlocker(
                dataset_name = '',
                dataset_uuid = ''
            )
        else:
            return ApphubV1EnvironmentSpecBuilderPodspecVolumesInnerFlocker(
        )
        """

    def testApphubV1EnvironmentSpecBuilderPodspecVolumesInnerFlocker(self):
        """Test ApphubV1EnvironmentSpecBuilderPodspecVolumesInnerFlocker"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
