# coding: utf-8

"""
    apphub

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from apphub_client.models.apphub_v1_function_spec_invoke_strategy_execution_strategy_hpa_behavior import ApphubV1FunctionSpecInvokeStrategyExecutionStrategyHpaBehavior

class TestApphubV1FunctionSpecInvokeStrategyExecutionStrategyHpaBehavior(unittest.TestCase):
    """ApphubV1FunctionSpecInvokeStrategyExecutionStrategyHpaBehavior unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApphubV1FunctionSpecInvokeStrategyExecutionStrategyHpaBehavior:
        """Test ApphubV1FunctionSpecInvokeStrategyExecutionStrategyHpaBehavior
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApphubV1FunctionSpecInvokeStrategyExecutionStrategyHpaBehavior`
        """
        model = ApphubV1FunctionSpecInvokeStrategyExecutionStrategyHpaBehavior()
        if include_optional:
            return ApphubV1FunctionSpecInvokeStrategyExecutionStrategyHpaBehavior(
                scale_down = apphub_client.models.apphub_v1_function_spec_invoke_strategy_execution_strategy_hpa_behavior_scale_down.apphub_v1_Function_spec_InvokeStrategy_ExecutionStrategy_hpaBehavior_scaleDown(
                    policies = [
                        apphub_client.models.apphub_v1_function_spec_invoke_strategy_execution_strategy_hpa_behavior_scale_down_policies_inner.apphub_v1_Function_spec_InvokeStrategy_ExecutionStrategy_hpaBehavior_scaleDown_policies_inner(
                            period_seconds = 56, 
                            type = '', 
                            value = 56, )
                        ], 
                    select_policy = '', 
                    stabilization_window_seconds = 56, ),
                scale_up = apphub_client.models.apphub_v1_function_spec_invoke_strategy_execution_strategy_hpa_behavior_scale_up.apphub_v1_Function_spec_InvokeStrategy_ExecutionStrategy_hpaBehavior_scaleUp(
                    policies = [
                        apphub_client.models.apphub_v1_function_spec_invoke_strategy_execution_strategy_hpa_behavior_scale_down_policies_inner.apphub_v1_Function_spec_InvokeStrategy_ExecutionStrategy_hpaBehavior_scaleDown_policies_inner(
                            period_seconds = 56, 
                            type = '', 
                            value = 56, )
                        ], 
                    select_policy = '', 
                    stabilization_window_seconds = 56, )
            )
        else:
            return ApphubV1FunctionSpecInvokeStrategyExecutionStrategyHpaBehavior(
        )
        """

    def testApphubV1FunctionSpecInvokeStrategyExecutionStrategyHpaBehavior(self):
        """Test ApphubV1FunctionSpecInvokeStrategyExecutionStrategyHpaBehavior"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
