from enum import Enum


class OrderConfirmationStatus1Code(Enum):
    STNP = "STNP"
    CPNP = "CPNP"
    COAC = "COAC"
    CREC = "CREC"


class RejectedConfirmationStatusReason1Code(Enum):
    DSAF = "DSAF"
    DFIN = "DFIN"
    DBEN = "DBEN"
    DPTD = "DPTD"
    DORD = "DORD"
    DCXR = "DCXR"
    DUNB = "DUNB"
    DORT = "DORT"
    DROU = "DROU"
    DNAM = "DNAM"
    DGAM = "DGAM"
    DHRR = "DHRR"
    DGRP = "DGRP"
    DINP = "DINP"
    DLIR = "DLIR"
    DARR = "DARR"
    DPDI = "DPDI"
    DRSC = "DRSC"
    DNAV = "DNAV"
    DFXD = "DFXD"
    DCHD = "DCHD"
    DXOD = "DXOD"
    DTAD = "DTAD"
    DPDD = "DPDD"
    DSCA = "DSCA"
    DPID = "DPID"
    DSAM = "DSAM"
    DSDT = "DSDT"
    DEXD = "DEXD"
    DIMD = "DIMD"
    DTRA = "DTRA"
    DTSA = "DTSA"
    DACI = "DACI"
    DACO = "DACO"
    DPSA = "DPSA"
    DPRA = "DPRA"
    DLID = "DLID"
    DORF = "DORF"
    ULNK = "ULNK"
    DREF = "DREF"
    IVAG = "IVAG"
    IRCU = "IRCU"
    IRIN = "IRIN"
    ICAG = "ICAG"
    IDCU = "IDCU"
    IDIN = "IDIN"
    ICTR = "ICTR"
    DMON = "DMON"
    DDAT = "DDAT"
    NSLA = "NSLA"
    MEUT = "MEUT"
    MCOM = "MCOM"
    MCHA = "MCHA"
    MTAX = "MTAX"
    NATA = "NATA"
    ALAT = "ALAT"
