
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-16T11:41:22+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "bf1c43ef0f1f583caafe0dfb885e529a843e805e",
 "version": "1.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
