from enum import Enum


class BalanceStatus1Code(Enum):
    PDNG = "PDNG"
    STLD = "STLD"


class ProcessingType1Code(Enum):
    RJCT = "RJCT"
    CVHD = "CVHD"
    RSVT = "RSVT"
    BLCK = "BLCK"
    EARM = "EARM"
    EFAC = "EFAC"
    DLVR = "DLVR"
    COLD = "COLD"
    CSDB = "CSDB"


class SystemBalanceType2Code(Enum):
    OPNG = "OPNG"
    INTM = "INTM"
    CLSG = "CLSG"
    BOOK = "BOOK"
    CRRT = "CRRT"
    PDNG = "PDNG"
    LRLD = "LRLD"
    AVLB = "AVLB"
    LTSF = "LTSF"
    CRDT = "CRDT"
    EAST = "EAST"
    PYMT = "PYMT"
    BLCK = "BLCK"
    XPCD = "XPCD"
    DLOD = "DLOD"
    XCRD = "XCRD"
    XDBT = "XDBT"
    ADJT = "ADJT"
    PRAV = "PRAV"
    DBIT = "DBIT"
    THRE = "THRE"
    NOTE = "NOTE"
    FSET = "FSET"
    BLOC = "BLOC"
    OTHB = "OTHB"
    CUST = "CUST"
    FORC = "FORC"
    COLC = "COLC"
    FUND = "FUND"
    PIPO = "PIPO"
    XCHG = "XCHG"
    CCPS = "CCPS"
    TOHB = "TOHB"
    COHB = "COHB"
    DOHB = "DOHB"
    TPBL = "TPBL"
    CPBL = "CPBL"
    DPBL = "DPBL"
    FUTB = "FUTB"
    REJB = "REJB"
    FCOL = "FCOL"
    FCOU = "FCOU"
    SCOL = "SCOL"
    SCOU = "SCOU"
    CUSA = "CUSA"
    XCHC = "XCHC"
    XCHN = "XCHN"
    DSET = "DSET"
    LACK = "LACK"
    NSET = "NSET"
    OTCC = "OTCC"
    OTCG = "OTCG"
    OTCN = "OTCN"
    SAPD = "SAPD"
    SAPC = "SAPC"
    REPD = "REPD"
    REPC = "REPC"
    BSCD = "BSCD"
    BSCC = "BSCC"
    SAPP = "SAPP"
    IRLT = "IRLT"
    IRDR = "IRDR"
    DWRD = "DWRD"
    ADWR = "ADWR"
    AIDR = "AIDR"
