
# **********************************************************************
# This file has been auto-generated by a code generation tool.
# Version:   4.2.2
# Date/time: 14 Jan 2025 12:06:07
# Template:  templates/pythonpws/version.razor.
# **********************************************************************

__version__ = "4.2.2"