from setuptools import setup, find_packages

with open("README.md", "r") as f:
    description = f.read()

setup(
    name='regpnlpypi',
    version='1.0',
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        'beautifulsoup4==4.12.3',
        'build==1.2.1',
        'DatastreamPy==2.0.21',
        'debugpy==1.8.1',
        'executing==2.0.1',
        'Markdown==3.7',
        'markdown-it-py==3.0.0',
        'holidays==0.63',
        'html5lib==1.1',
        'matplotlib==3.8.0',
        'matplotlib-inline==0.1.7',
        'mypy-extensions==1.0.0',
        'numpy==1.26.4',
        'oauthlib==3.2.2',
        'packaging==23.2',
        'pip==24.3.1',
        'pandas==2.2.3',
        'pandas-datareader==0.10.0',
        'pybacktestchain==0.2.1',
        'PyDatastream==0.6.5',
        'python-dateutil==2.8.2',
        'requests==2.31.0',
        'scikit-learn==1.2.2',
        'scipy==1.11.3',
        'statsmodels==0.14.4',
        'streamlit==1.41.1',
        'textblob==0.18.0.post0',
        'types-python-dateutil==2.9.0.20241206',
        'typing_extensions==4.12.2',
        'urllib3==2.2.1',
        'virtualenv==20.26.3',
        'yfinance==0.2.51',
        'setuptools==75.8.0',
        'setuptools-scm==8.1.0',
        'numba==0.60.0',
        'pytest==8.3.4',
        'python-json-logger==3.2.1',
        'cloudpickle==3.1.0',
        'sec-cik-mapper==2.1.0',
    ],
    long_description=description,
    long_description_content_type="text/markdown",
)
