"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
import typing

try:
    import yandex.cloud.priv.iam.v1.workload.oidc.federation_pb2
except ImportError:
    import datasphere.yandex.cloud.priv.iam.v1.workload.oidc.federation_pb2


try:
    import yandex.cloud.priv.iam.v1.workload.oidc.federation_service_pb2
except ImportError:
    import datasphere.yandex.cloud.priv.iam.v1.workload.oidc.federation_service_pb2


try:
    import yandex.cloud.priv.operation.operation_pb2
except ImportError:
    import datasphere.yandex.cloud.priv.operation.operation_pb2


_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class FederationServiceStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    Get: grpc.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.workload.oidc.federation_service_pb2.GetFederationRequest,
        yandex.cloud.priv.iam.v1.workload.oidc.federation_pb2.Federation,
    ]

    Create: grpc.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.workload.oidc.federation_service_pb2.CreateFederationRequest,
        yandex.cloud.priv.operation.operation_pb2.Operation,
    ]

    Update: grpc.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.workload.oidc.federation_service_pb2.UpdateFederationRequest,
        yandex.cloud.priv.operation.operation_pb2.Operation,
    ]

    Delete: grpc.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.workload.oidc.federation_service_pb2.DeleteFederationRequest,
        yandex.cloud.priv.operation.operation_pb2.Operation,
    ]

    List: grpc.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.workload.oidc.federation_service_pb2.ListFederationsRequest,
        yandex.cloud.priv.iam.v1.workload.oidc.federation_service_pb2.ListFederationsResponse,
    ]

class FederationServiceAsyncStub:
    Get: grpc.aio.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.workload.oidc.federation_service_pb2.GetFederationRequest,
        yandex.cloud.priv.iam.v1.workload.oidc.federation_pb2.Federation,
    ]

    Create: grpc.aio.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.workload.oidc.federation_service_pb2.CreateFederationRequest,
        yandex.cloud.priv.operation.operation_pb2.Operation,
    ]

    Update: grpc.aio.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.workload.oidc.federation_service_pb2.UpdateFederationRequest,
        yandex.cloud.priv.operation.operation_pb2.Operation,
    ]

    Delete: grpc.aio.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.workload.oidc.federation_service_pb2.DeleteFederationRequest,
        yandex.cloud.priv.operation.operation_pb2.Operation,
    ]

    List: grpc.aio.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.workload.oidc.federation_service_pb2.ListFederationsRequest,
        yandex.cloud.priv.iam.v1.workload.oidc.federation_service_pb2.ListFederationsResponse,
    ]

class FederationServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Get(
        self,
        request: yandex.cloud.priv.iam.v1.workload.oidc.federation_service_pb2.GetFederationRequest,
        context: _ServicerContext,
    ) -> typing.Union[yandex.cloud.priv.iam.v1.workload.oidc.federation_pb2.Federation, collections.abc.Awaitable[yandex.cloud.priv.iam.v1.workload.oidc.federation_pb2.Federation]]: ...

    @abc.abstractmethod
    def Create(
        self,
        request: yandex.cloud.priv.iam.v1.workload.oidc.federation_service_pb2.CreateFederationRequest,
        context: _ServicerContext,
    ) -> typing.Union[yandex.cloud.priv.operation.operation_pb2.Operation, collections.abc.Awaitable[yandex.cloud.priv.operation.operation_pb2.Operation]]: ...

    @abc.abstractmethod
    def Update(
        self,
        request: yandex.cloud.priv.iam.v1.workload.oidc.federation_service_pb2.UpdateFederationRequest,
        context: _ServicerContext,
    ) -> typing.Union[yandex.cloud.priv.operation.operation_pb2.Operation, collections.abc.Awaitable[yandex.cloud.priv.operation.operation_pb2.Operation]]: ...

    @abc.abstractmethod
    def Delete(
        self,
        request: yandex.cloud.priv.iam.v1.workload.oidc.federation_service_pb2.DeleteFederationRequest,
        context: _ServicerContext,
    ) -> typing.Union[yandex.cloud.priv.operation.operation_pb2.Operation, collections.abc.Awaitable[yandex.cloud.priv.operation.operation_pb2.Operation]]: ...

    @abc.abstractmethod
    def List(
        self,
        request: yandex.cloud.priv.iam.v1.workload.oidc.federation_service_pb2.ListFederationsRequest,
        context: _ServicerContext,
    ) -> typing.Union[yandex.cloud.priv.iam.v1.workload.oidc.federation_service_pb2.ListFederationsResponse, collections.abc.Awaitable[yandex.cloud.priv.iam.v1.workload.oidc.federation_service_pb2.ListFederationsResponse]]: ...

def add_FederationServiceServicer_to_server(servicer: FederationServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
