"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

try:
    import yandex.cloud.priv.datasphere.v2.nodedeployer.healthcheck_pb2
except ImportError:
    import datasphere.yandex.cloud.priv.datasphere.v2.nodedeployer.healthcheck_pb2


try:
    import yandex.cloud.priv.datasphere.v2.nodedeployer.runtime_options_pb2
except ImportError:
    import datasphere.yandex.cloud.priv.datasphere.v2.nodedeployer.runtime_options_pb2


if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class DockerApp(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTAINER_FIELD_NUMBER: builtins.int
    ENDPOINT_FIELD_NUMBER: builtins.int
    TELEMETRY_FIELD_NUMBER: builtins.int
    HEALTHCHECK_FIELD_NUMBER: builtins.int
    RUNTIME_OPTIONS_FIELD_NUMBER: builtins.int
    @property
    def container(self) -> global___Container: ...
    @property
    def endpoint(self) -> global___Endpoint: ...
    @property
    def telemetry(self) -> global___Telemetry: ...
    @property
    def healthcheck(self) -> yandex.cloud.priv.datasphere.v2.nodedeployer.healthcheck_pb2.Healthcheck: ...
    @property
    def runtime_options(self) -> yandex.cloud.priv.datasphere.v2.nodedeployer.runtime_options_pb2.RuntimeOptions: ...
    def __init__(
        self,
        *,
        container: global___Container | None = ...,
        endpoint: global___Endpoint | None = ...,
        telemetry: global___Telemetry | None = ...,
        healthcheck: yandex.cloud.priv.datasphere.v2.nodedeployer.healthcheck_pb2.Healthcheck | None = ...,
        runtime_options: yandex.cloud.priv.datasphere.v2.nodedeployer.runtime_options_pb2.RuntimeOptions | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["container", b"container", "endpoint", b"endpoint", "healthcheck", b"healthcheck", "runtime_options", b"runtime_options", "telemetry", b"telemetry"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["container", b"container", "endpoint", b"endpoint", "healthcheck", b"healthcheck", "runtime_options", b"runtime_options", "telemetry", b"telemetry"]) -> None: ...

global___DockerApp = DockerApp

@typing.final
class Endpoint(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PORT_FIELD_NUMBER: builtins.int
    ENDPOINT_OPTIONS_FIELD_NUMBER: builtins.int
    TIMEOUT_FIELD_NUMBER: builtins.int
    IDLE_TIMEOUT_FIELD_NUMBER: builtins.int
    port: builtins.int
    @property
    def endpoint_options(self) -> global___EndpointOptions: ...
    @property
    def timeout(self) -> google.protobuf.duration_pb2.Duration: ...
    @property
    def idle_timeout(self) -> google.protobuf.duration_pb2.Duration: ...
    def __init__(
        self,
        *,
        port: builtins.int = ...,
        endpoint_options: global___EndpointOptions | None = ...,
        timeout: google.protobuf.duration_pb2.Duration | None = ...,
        idle_timeout: google.protobuf.duration_pb2.Duration | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["endpoint_options", b"endpoint_options", "idle_timeout", b"idle_timeout", "timeout", b"timeout"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["endpoint_options", b"endpoint_options", "idle_timeout", b"idle_timeout", "port", b"port", "timeout", b"timeout"]) -> None: ...

global___Endpoint = Endpoint

@typing.final
class Container(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IMAGE_FIELD_NUMBER: builtins.int
    USERNAME_FIELD_NUMBER: builtins.int
    PASSWORD_SECRET_FIELD_NUMBER: builtins.int
    PORTS_FIELD_NUMBER: builtins.int
    PASSWORD_SECRET_ID_FIELD_NUMBER: builtins.int
    image: builtins.str
    username: builtins.str
    password_secret: builtins.str
    password_secret_id: builtins.str
    @property
    def ports(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ContainerPort]: ...
    def __init__(
        self,
        *,
        image: builtins.str = ...,
        username: builtins.str = ...,
        password_secret: builtins.str = ...,
        ports: collections.abc.Iterable[global___ContainerPort] | None = ...,
        password_secret_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["image", b"image", "password_secret", b"password_secret", "password_secret_id", b"password_secret_id", "ports", b"ports", "username", b"username"]) -> None: ...

global___Container = Container

@typing.final
class ContainerPort(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTAINER_PORT_FIELD_NUMBER: builtins.int
    HOST_PORT_FIELD_NUMBER: builtins.int
    HOST_IP_FIELD_NUMBER: builtins.int
    PROTOCOL_FIELD_NUMBER: builtins.int
    container_port: builtins.int
    host_port: builtins.int
    host_ip: builtins.str
    protocol: builtins.str
    def __init__(
        self,
        *,
        container_port: builtins.int = ...,
        host_port: builtins.int = ...,
        host_ip: builtins.str = ...,
        protocol: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["container_port", b"container_port", "host_ip", b"host_ip", "host_port", b"host_port", "protocol", b"protocol"]) -> None: ...

global___ContainerPort = ContainerPort

@typing.final
class EndpointOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HTTP_FIELD_NUMBER: builtins.int
    GRPC_FIELD_NUMBER: builtins.int
    @property
    def http(self) -> global___HttpEndpoint: ...
    @property
    def grpc(self) -> global___GrpcEndpoint: ...
    def __init__(
        self,
        *,
        http: global___HttpEndpoint | None = ...,
        grpc: global___GrpcEndpoint | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["endpoint_type", b"endpoint_type", "grpc", b"grpc", "http", b"http"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["endpoint_type", b"endpoint_type", "grpc", b"grpc", "http", b"http"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["endpoint_type", b"endpoint_type"]) -> typing.Literal["http", "grpc"] | None: ...

global___EndpointOptions = EndpointOptions

@typing.final
class HttpEndpoint(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USE_HTTP2_FIELD_NUMBER: builtins.int
    use_http2: builtins.bool
    def __init__(
        self,
        *,
        use_http2: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["use_http2", b"use_http2"]) -> None: ...

global___HttpEndpoint = HttpEndpoint

@typing.final
class GrpcEndpoint(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___GrpcEndpoint = GrpcEndpoint

@typing.final
class ProtocolOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EXPLICIT_PROTOCOL_CONFIG_FIELD_NUMBER: builtins.int
    @property
    def explicit_protocol_config(self) -> global___ExplicitProtocolConfig: ...
    def __init__(
        self,
        *,
        explicit_protocol_config: global___ExplicitProtocolConfig | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["explicit_protocol_config", b"explicit_protocol_config", "upstream_protocol", b"upstream_protocol"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["explicit_protocol_config", b"explicit_protocol_config", "upstream_protocol", b"upstream_protocol"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["upstream_protocol", b"upstream_protocol"]) -> typing.Literal["explicit_protocol_config"] | None: ...

global___ProtocolOptions = ProtocolOptions

@typing.final
class ExplicitProtocolConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HTTP1_PROTOCOL_CONFIG_FIELD_NUMBER: builtins.int
    HTTP2_PROTOCOL_CONFIG_FIELD_NUMBER: builtins.int
    @property
    def http1_protocol_config(self) -> global___Http1ProtocolConfig: ...
    @property
    def http2_protocol_config(self) -> global___Http2ProtocolConfig: ...
    def __init__(
        self,
        *,
        http1_protocol_config: global___Http1ProtocolConfig | None = ...,
        http2_protocol_config: global___Http2ProtocolConfig | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["http1_protocol_config", b"http1_protocol_config", "http2_protocol_config", b"http2_protocol_config", "protocol", b"protocol"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["http1_protocol_config", b"http1_protocol_config", "http2_protocol_config", b"http2_protocol_config", "protocol", b"protocol"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["protocol", b"protocol"]) -> typing.Literal["http1_protocol_config", "http2_protocol_config"] | None: ...

global___ExplicitProtocolConfig = ExplicitProtocolConfig

@typing.final
class Http1ProtocolConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___Http1ProtocolConfig = Http1ProtocolConfig

@typing.final
class Http2ProtocolConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___Http2ProtocolConfig = Http2ProtocolConfig

@typing.final
class Telemetry(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Format:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _FormatEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Telemetry._Format.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        FORMAT_UNSPECIFIED: Telemetry._Format.ValueType  # 0
        SOLOMON_JSON: Telemetry._Format.ValueType  # 1
        PROMETHEUS: Telemetry._Format.ValueType  # 2

    class Format(_Format, metaclass=_FormatEnumTypeWrapper): ...
    FORMAT_UNSPECIFIED: Telemetry.Format.ValueType  # 0
    SOLOMON_JSON: Telemetry.Format.ValueType  # 1
    PROMETHEUS: Telemetry.Format.ValueType  # 2

    PATH_FIELD_NUMBER: builtins.int
    PORT_FIELD_NUMBER: builtins.int
    FORMAT_FIELD_NUMBER: builtins.int
    path: builtins.str
    port: builtins.int
    format: global___Telemetry.Format.ValueType
    def __init__(
        self,
        *,
        path: builtins.str = ...,
        port: builtins.int = ...,
        format: global___Telemetry.Format.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["format", b"format", "path", b"path", "port", b"port"]) -> None: ...

global___Telemetry = Telemetry
