"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import google.protobuf.empty_pb2
import grpc
import grpc.aio
import typing

try:
    import yandex.cloud.priv.iam.v1.mfa.profile.mfa_profile_service_pb2
except ImportError:
    import datasphere.yandex.cloud.priv.iam.v1.mfa.profile.mfa_profile_service_pb2


try:
    import yandex.cloud.priv.operation.operation_pb2
except ImportError:
    import datasphere.yandex.cloud.priv.operation.operation_pb2


_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class MfaProfileServiceStub:
    """A set of methods for managing mfa profiles.
    The user credentials should be passed in the authorization header.
    """

    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    GetProfilesConfig: grpc.UnaryUnaryMultiCallable[
        google.protobuf.empty_pb2.Empty,
        yandex.cloud.priv.iam.v1.mfa.profile.mfa_profile_service_pb2.GetProfilesConfigResponse,
    ]
    """Returns allowed mfa profile types and configured mfa profiles."""

    DeleteAllPofilesForSubject: grpc.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.mfa.profile.mfa_profile_service_pb2.DeleteAllPofilesForSubjectRequest,
        yandex.cloud.priv.operation.operation_pb2.Operation,
    ]
    """Delete all mfa profiles for specified user.
    This method requires `iam.mfaProfiles.delete` permission.
    """

class MfaProfileServiceAsyncStub:
    """A set of methods for managing mfa profiles.
    The user credentials should be passed in the authorization header.
    """

    GetProfilesConfig: grpc.aio.UnaryUnaryMultiCallable[
        google.protobuf.empty_pb2.Empty,
        yandex.cloud.priv.iam.v1.mfa.profile.mfa_profile_service_pb2.GetProfilesConfigResponse,
    ]
    """Returns allowed mfa profile types and configured mfa profiles."""

    DeleteAllPofilesForSubject: grpc.aio.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.mfa.profile.mfa_profile_service_pb2.DeleteAllPofilesForSubjectRequest,
        yandex.cloud.priv.operation.operation_pb2.Operation,
    ]
    """Delete all mfa profiles for specified user.
    This method requires `iam.mfaProfiles.delete` permission.
    """

class MfaProfileServiceServicer(metaclass=abc.ABCMeta):
    """A set of methods for managing mfa profiles.
    The user credentials should be passed in the authorization header.
    """

    @abc.abstractmethod
    def GetProfilesConfig(
        self,
        request: google.protobuf.empty_pb2.Empty,
        context: _ServicerContext,
    ) -> typing.Union[yandex.cloud.priv.iam.v1.mfa.profile.mfa_profile_service_pb2.GetProfilesConfigResponse, collections.abc.Awaitable[yandex.cloud.priv.iam.v1.mfa.profile.mfa_profile_service_pb2.GetProfilesConfigResponse]]:
        """Returns allowed mfa profile types and configured mfa profiles."""

    @abc.abstractmethod
    def DeleteAllPofilesForSubject(
        self,
        request: yandex.cloud.priv.iam.v1.mfa.profile.mfa_profile_service_pb2.DeleteAllPofilesForSubjectRequest,
        context: _ServicerContext,
    ) -> typing.Union[yandex.cloud.priv.operation.operation_pb2.Operation, collections.abc.Awaitable[yandex.cloud.priv.operation.operation_pb2.Operation]]:
        """Delete all mfa profiles for specified user.
        This method requires `iam.mfaProfiles.delete` permission.
        """

def add_MfaProfileServiceServicer_to_server(servicer: MfaProfileServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
