"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Subject(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class UserAccount(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ID_FIELD_NUMBER: builtins.int
        id: builtins.str
        def __init__(
            self,
            *,
            id: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["id", b"id"]) -> None: ...

    @typing.final
    class ServiceAccount(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ID_FIELD_NUMBER: builtins.int
        id: builtins.str
        def __init__(
            self,
            *,
            id: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["id", b"id"]) -> None: ...

    USER_ACCOUNT_FIELD_NUMBER: builtins.int
    SERVICE_ACCOUNT_FIELD_NUMBER: builtins.int
    @property
    def user_account(self) -> global___Subject.UserAccount: ...
    @property
    def service_account(self) -> global___Subject.ServiceAccount: ...
    def __init__(
        self,
        *,
        user_account: global___Subject.UserAccount | None = ...,
        service_account: global___Subject.ServiceAccount | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["service_account", b"service_account", "type", b"type", "user_account", b"user_account"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["service_account", b"service_account", "type", b"type", "user_account", b"user_account"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["type", b"type"]) -> typing.Literal["user_account", "service_account"] | None: ...

global___Subject = Subject
