# coding: utf-8

"""
    apphub

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from apphub_client.models.apphub_v1_environment_spec_builder_container_lifecycle_post_start import ApphubV1EnvironmentSpecBuilderContainerLifecyclePostStart

class TestApphubV1EnvironmentSpecBuilderContainerLifecyclePostStart(unittest.TestCase):
    """ApphubV1EnvironmentSpecBuilderContainerLifecyclePostStart unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApphubV1EnvironmentSpecBuilderContainerLifecyclePostStart:
        """Test ApphubV1EnvironmentSpecBuilderContainerLifecyclePostStart
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApphubV1EnvironmentSpecBuilderContainerLifecyclePostStart`
        """
        model = ApphubV1EnvironmentSpecBuilderContainerLifecyclePostStart()
        if include_optional:
            return ApphubV1EnvironmentSpecBuilderContainerLifecyclePostStart(
                var_exec = apphub_client.models.apphub_v1_environment_spec_builder_container_lifecycle_post_start_exec.apphub_v1_Environment_spec_builder_container_lifecycle_postStart_exec(
                    command = [
                        ''
                        ], ),
                http_get = apphub_client.models.apphub_v1_environment_spec_builder_container_lifecycle_post_start_http_get.apphub_v1_Environment_spec_builder_container_lifecycle_postStart_httpGet(
                    host = '', 
                    http_headers = [
                        apphub_client.models.apphub_v1_environment_spec_builder_container_lifecycle_post_start_http_get_http_headers_inner.apphub_v1_Environment_spec_builder_container_lifecycle_postStart_httpGet_httpHeaders_inner(
                            name = '', 
                            value = '', )
                        ], 
                    path = '', 
                    port = apphub_client.models.port.port(), 
                    scheme = '', ),
                sleep = apphub_client.models.apphub_v1_environment_spec_builder_container_lifecycle_post_start_sleep.apphub_v1_Environment_spec_builder_container_lifecycle_postStart_sleep(
                    seconds = 56, ),
                tcp_socket = apphub_client.models.apphub_v1_environment_spec_builder_container_lifecycle_post_start_tcp_socket.apphub_v1_Environment_spec_builder_container_lifecycle_postStart_tcpSocket(
                    host = '', 
                    port = apphub_client.models.port.port(), )
            )
        else:
            return ApphubV1EnvironmentSpecBuilderContainerLifecyclePostStart(
        )
        """

    def testApphubV1EnvironmentSpecBuilderContainerLifecyclePostStart(self):
        """Test ApphubV1EnvironmentSpecBuilderContainerLifecyclePostStart"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
