# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'reservar.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDateEdit,
    QFrame, QGroupBox, QLabel, QLineEdit,
    QPushButton, QSizePolicy, QWidget)

from ..imagenes import imagenes_rc

class Ui_JTA_Reservar(object):
    def setupUi(self, JTA_Reservar):
        if not JTA_Reservar.objectName():
            JTA_Reservar.setObjectName(u"JTA_Reservar")
        JTA_Reservar.resize(693, 603)
        JTA_Reservar.setMinimumSize(QSize(693, 603))
        JTA_Reservar.setMaximumSize(QSize(693, 603))
        palette = QPalette()
        brush = QBrush(QColor(0, 85, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush)
        brush1 = QBrush(QColor(255, 170, 0, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush)
        JTA_Reservar.setPalette(palette)
        icon = QIcon()
        icon.addFile(u":/imagenes/icon.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        JTA_Reservar.setWindowIcon(icon)
        JTA_Reservar.setStyleSheet(u"")
        self.JTA_frame = QFrame(JTA_Reservar)
        self.JTA_frame.setObjectName(u"JTA_frame")
        self.JTA_frame.setGeometry(QRect(0, 0, 781, 651))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.JTA_frame.sizePolicy().hasHeightForWidth())
        self.JTA_frame.setSizePolicy(sizePolicy)
        self.JTA_frame.setMinimumSize(QSize(781, 0))
        self.JTA_frame.setMaximumSize(QSize(781, 651))
        self.JTA_frame.setStyleSheet(u"background-color: #f0dfc7;")
        self.JTA_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.JTA_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.JTA_pushButton_reservar = QPushButton(self.JTA_frame)
        self.JTA_pushButton_reservar.setObjectName(u"JTA_pushButton_reservar")
        self.JTA_pushButton_reservar.setGeometry(QRect(450, 520, 231, 61))
        font = QFont()
        font.setFamilies([u"Arial Rounded MT"])
        font.setPointSize(16)
        font.setBold(True)
        self.JTA_pushButton_reservar.setFont(font)
        self.JTA_pushButton_reservar.setStyleSheet(u"QPushButton {\n"
"    border: 2px solid #78ac75;\n"
"    border-radius: 25px;\n"
"    background-color: #9fd079;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #a4c59d;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #597354;\n"
"}\n"
"")
        self.JTA_pushButton_actualizares = QPushButton(self.JTA_frame)
        self.JTA_pushButton_actualizares.setObjectName(u"JTA_pushButton_actualizares")
        self.JTA_pushButton_actualizares.setGeometry(QRect(10, 520, 281, 61))
        self.JTA_pushButton_actualizares.setFont(font)
        self.JTA_pushButton_actualizares.setStyleSheet(u"QPushButton {\n"
"    border: 2px solid #78ac75;\n"
"    border-radius: 25px;\n"
"    background-color: #9fd079;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #a4c59d;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #597354;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #7a8c68;\n"
"    color: #cccccc; \n"
"    border: 2px solid #667556; \n"
"}")
        self.JTA_groupBox_datres = QGroupBox(self.JTA_frame)
        self.JTA_groupBox_datres.setObjectName(u"JTA_groupBox_datres")
        self.JTA_groupBox_datres.setGeometry(QRect(10, 210, 671, 291))
        self.JTA_dateEdit_fecha = QDateEdit(self.JTA_groupBox_datres)
        self.JTA_dateEdit_fecha.setObjectName(u"JTA_dateEdit_fecha")
        self.JTA_dateEdit_fecha.setGeometry(QRect(210, 30, 271, 31))
        font1 = QFont()
        font1.setPointSize(12)
        self.JTA_dateEdit_fecha.setFont(font1)
        self.JTA_dateEdit_fecha.setMinimumDateTime(QDateTime(QDate(2019, 9, 14), QTime(13, 0, 0)))
        self.JTA_dateEdit_fecha.setMaximumDate(QDate(2028, 12, 31))
        self.JTA_dateEdit_fecha.setMinimumDate(QDate(2019, 9, 14))
        self.JTA_dateEdit_fecha.setDate(QDate(2024, 10, 1))
        self.JTA_comboBox_tipores = QComboBox(self.JTA_groupBox_datres)
        self.JTA_comboBox_tipores.setObjectName(u"JTA_comboBox_tipores")
        self.JTA_comboBox_tipores.setGeometry(QRect(210, 80, 271, 31))
        self.JTA_comboBox_tipores.setStyleSheet(u"JTA_comboBox_tipores {\n"
"background-color: #ffffff\n"
"}")
        self.JTA_label_numpersonas = QLabel(self.JTA_groupBox_datres)
        self.JTA_label_numpersonas.setObjectName(u"JTA_label_numpersonas")
        self.JTA_label_numpersonas.setGeometry(QRect(20, 160, 151, 41))
        font2 = QFont()
        font2.setFamilies([u"Sitka"])
        font2.setPointSize(12)
        font2.setBold(False)
        font2.setItalic(False)
        self.JTA_label_numpersonas.setFont(font2)
        self.JTA_label_numpersonas.setStyleSheet(u"font: 12pt \"Sitka\";")
        self.JTA_label_fecha = QLabel(self.JTA_groupBox_datres)
        self.JTA_label_fecha.setObjectName(u"JTA_label_fecha")
        self.JTA_label_fecha.setGeometry(QRect(20, 20, 151, 41))
        self.JTA_label_fecha.setFont(font2)
        self.JTA_label_fecha.setStyleSheet(u"font: 12pt \"Sitka\";")
        self.JTA_checkBox_habnecesarias = QCheckBox(self.JTA_groupBox_datres)
        self.JTA_checkBox_habnecesarias.setObjectName(u"JTA_checkBox_habnecesarias")
        self.JTA_checkBox_habnecesarias.setGeometry(QRect(390, 120, 121, 21))
        font3 = QFont()
        font3.setPointSize(10)
        self.JTA_checkBox_habnecesarias.setFont(font3)
        self.JTA_label_tiporeserva = QLabel(self.JTA_groupBox_datres)
        self.JTA_label_tiporeserva.setObjectName(u"JTA_label_tiporeserva")
        self.JTA_label_tiporeserva.setGeometry(QRect(20, 70, 151, 41))
        self.JTA_label_tiporeserva.setFont(font2)
        self.JTA_label_tiporeserva.setStyleSheet(u"font: 12pt \"Sitka\";")
        self.JTA_label_habnecesarias = QLabel(self.JTA_groupBox_datres)
        self.JTA_label_habnecesarias.setObjectName(u"JTA_label_habnecesarias")
        self.JTA_label_habnecesarias.setGeometry(QRect(210, 110, 181, 41))
        font4 = QFont()
        font4.setFamilies([u"Sitka"])
        font4.setPointSize(9)
        font4.setBold(False)
        font4.setItalic(False)
        self.JTA_label_habnecesarias.setFont(font4)
        self.JTA_label_habnecesarias.setStyleSheet(u"font: 9pt \"Sitka\";")
        self.JTA_label_tipococina = QLabel(self.JTA_groupBox_datres)
        self.JTA_label_tipococina.setObjectName(u"JTA_label_tipococina")
        self.JTA_label_tipococina.setGeometry(QRect(20, 210, 151, 41))
        self.JTA_label_tipococina.setFont(font2)
        self.JTA_label_tipococina.setStyleSheet(u"font: 12pt \"Sitka\";")
        self.JTA_lineEdit_numpersonas = QLineEdit(self.JTA_groupBox_datres)
        self.JTA_lineEdit_numpersonas.setObjectName(u"JTA_lineEdit_numpersonas")
        self.JTA_lineEdit_numpersonas.setGeometry(QRect(210, 170, 81, 31))
        self.JTA_lineEdit_numpersonas.setFont(font1)
        self.JTA_lineEdit_numpersonas.setStyleSheet(u"")
        self.JTA_lineEdit_numpersonas.setMaxLength(100)
        self.JTA_lineEdit_jornadas = QLineEdit(self.JTA_groupBox_datres)
        self.JTA_lineEdit_jornadas.setObjectName(u"JTA_lineEdit_jornadas")
        self.JTA_lineEdit_jornadas.setGeometry(QRect(110, 120, 81, 31))
        self.JTA_lineEdit_jornadas.setFont(font3)
        self.JTA_lineEdit_jornadas.setStyleSheet(u"")
        self.JTA_lineEdit_jornadas.setMaxLength(100)
        self.JTA_label_jornadas = QLabel(self.JTA_groupBox_datres)
        self.JTA_label_jornadas.setObjectName(u"JTA_label_jornadas")
        self.JTA_label_jornadas.setGeometry(QRect(20, 110, 81, 41))
        self.JTA_label_jornadas.setFont(font4)
        self.JTA_label_jornadas.setStyleSheet(u"font: 9pt \"Sitka\";")
        self.JTA_comboBox_tipococina = QComboBox(self.JTA_groupBox_datres)
        self.JTA_comboBox_tipococina.setObjectName(u"JTA_comboBox_tipococina")
        self.JTA_comboBox_tipococina.setGeometry(QRect(210, 220, 271, 31))
        self.JTA_comboBox_tipococina.setStyleSheet(u"JTA_comboBox_tipococina {\n"
"background-color: #ffffff\n"
"}")
        self.JTA_line_linea = QFrame(self.JTA_frame)
        self.JTA_line_linea.setObjectName(u"JTA_line_linea")
        self.JTA_line_linea.setGeometry(QRect(-90, 500, 1101, 16))
        self.JTA_line_linea.setFrameShape(QFrame.Shape.HLine)
        self.JTA_line_linea.setFrameShadow(QFrame.Shadow.Sunken)
        self.JTA_groupBox_datcli = QGroupBox(self.JTA_frame)
        self.JTA_groupBox_datcli.setObjectName(u"JTA_groupBox_datcli")
        self.JTA_groupBox_datcli.setGeometry(QRect(10, 80, 671, 131))
        palette1 = QPalette()
        brush2 = QBrush(QColor(0, 0, 0, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        brush3 = QBrush(QColor(240, 223, 199, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush3)
        brush4 = QBrush(QColor(255, 255, 255, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Light, brush4)
        brush5 = QBrush(QColor(247, 239, 227, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Midlight, brush5)
        brush6 = QBrush(QColor(120, 111, 99, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Dark, brush6)
        brush7 = QBrush(QColor(160, 149, 133, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Mid, brush7)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette1.setBrush(QPalette.Active, QPalette.BrightText, brush4)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette1.setBrush(QPalette.Active, QPalette.Shadow, brush2)
        palette1.setBrush(QPalette.Active, QPalette.AlternateBase, brush5)
        brush8 = QBrush(QColor(255, 255, 220, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipText, brush2)
        brush9 = QBrush(QColor(0, 0, 0, 127))
        brush9.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush9)
#endif
        palette1.setBrush(QPalette.Active, QPalette.Accent, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.Light, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.Midlight, brush5)
        palette1.setBrush(QPalette.Inactive, QPalette.Dark, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.Mid, brush7)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.BrightText, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.Shadow, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush5)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush2)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush9)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.Accent, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush6)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush3)
        palette1.setBrush(QPalette.Disabled, QPalette.Light, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Midlight, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.Dark, brush6)
        palette1.setBrush(QPalette.Disabled, QPalette.Mid, brush7)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush6)
        palette1.setBrush(QPalette.Disabled, QPalette.BrightText, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush6)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        palette1.setBrush(QPalette.Disabled, QPalette.Shadow, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush3)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush2)
        brush10 = QBrush(QColor(120, 111, 99, 127))
        brush10.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush10)
#endif
        palette1.setBrush(QPalette.Disabled, QPalette.Accent, brush4)
        self.JTA_groupBox_datcli.setPalette(palette1)
        self.JTA_groupBox_datcli.setStyleSheet(u"")
        self.JTA_label_nombre = QLabel(self.JTA_groupBox_datcli)
        self.JTA_label_nombre.setObjectName(u"JTA_label_nombre")
        self.JTA_label_nombre.setGeometry(QRect(20, 20, 161, 41))
        self.JTA_label_nombre.setFont(font2)
        self.JTA_label_nombre.setStyleSheet(u"font: 12pt \"Sitka\";")
        self.JTA_lineEdit_telefono = QLineEdit(self.JTA_groupBox_datcli)
        self.JTA_lineEdit_telefono.setObjectName(u"JTA_lineEdit_telefono")
        self.JTA_lineEdit_telefono.setGeometry(QRect(210, 80, 371, 31))
        self.JTA_lineEdit_telefono.setFont(font1)
        self.JTA_lineEdit_telefono.setStyleSheet(u"")
        self.JTA_lineEdit_telefono.setMaxLength(9)
        self.JTA_lineEdit_nombre = QLineEdit(self.JTA_groupBox_datcli)
        self.JTA_lineEdit_nombre.setObjectName(u"JTA_lineEdit_nombre")
        self.JTA_lineEdit_nombre.setGeometry(QRect(210, 30, 371, 31))
        self.JTA_lineEdit_nombre.setFont(font1)
        self.JTA_lineEdit_nombre.setAutoFillBackground(False)
        self.JTA_lineEdit_nombre.setStyleSheet(u"")
        self.JTA_lineEdit_nombre.setMaxLength(100)
        self.JTA_label_telefono = QLabel(self.JTA_groupBox_datcli)
        self.JTA_label_telefono.setObjectName(u"JTA_label_telefono")
        self.JTA_label_telefono.setGeometry(QRect(20, 70, 181, 41))
        self.JTA_label_telefono.setFont(font2)
        self.JTA_label_telefono.setStyleSheet(u"font: 12pt \"Sitka\";")
        self.JTA_label_resicon = QLabel(self.JTA_frame)
        self.JTA_label_resicon.setObjectName(u"JTA_label_resicon")
        self.JTA_label_resicon.setGeometry(QRect(20, 20, 41, 41))
        self.JTA_label_resicon.setStyleSheet(u"background-color: transparent;")
        self.JTA_label_resicon.setPixmap(QPixmap(u":/imagenes/reserva.png"))
        self.JTA_label_resicon.setScaledContents(True)
        self.JTA_label_title = QLabel(self.JTA_frame)
        self.JTA_label_title.setObjectName(u"JTA_label_title")
        self.JTA_label_title.setGeometry(QRect(270, 30, 171, 31))
        font5 = QFont()
        font5.setFamilies([u"Candara"])
        font5.setPointSize(28)
        font5.setBold(True)
        font5.setItalic(False)
        self.JTA_label_title.setFont(font5)
        self.JTA_label_title.setStyleSheet(u"font: 700 28pt \"Candara\";\n"
"color: white;\n"
"background-color: transparent;")
        self.JTA_label_enc = QLabel(self.JTA_frame)
        self.JTA_label_enc.setObjectName(u"JTA_label_enc")
        self.JTA_label_enc.setGeometry(QRect(-10, -10, 711, 91))
        self.JTA_label_enc.setStyleSheet(u"background-color: #9fd079;")
        self.JTA_pushButton_volver = QPushButton(self.JTA_frame)
        self.JTA_pushButton_volver.setObjectName(u"JTA_pushButton_volver")
        self.JTA_pushButton_volver.setGeometry(QRect(620, 10, 61, 61))
        self.JTA_pushButton_volver.setStyleSheet(u"background-color: transparent;")
        icon1 = QIcon()
        icon1.addFile(u":/imagenes/volver.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.JTA_pushButton_volver.setIcon(icon1)
        self.JTA_pushButton_volver.setIconSize(QSize(40, 40))
        self.JTA_label_enc.raise_()
        self.JTA_pushButton_reservar.raise_()
        self.JTA_pushButton_actualizares.raise_()
        self.JTA_groupBox_datres.raise_()
        self.JTA_line_linea.raise_()
        self.JTA_groupBox_datcli.raise_()
        self.JTA_label_title.raise_()
        self.JTA_label_resicon.raise_()
        self.JTA_pushButton_volver.raise_()

        self.retranslateUi(JTA_Reservar)

        QMetaObject.connectSlotsByName(JTA_Reservar)
    # setupUi

    def retranslateUi(self, JTA_Reservar):
        JTA_Reservar.setWindowTitle(QCoreApplication.translate("JTA_Reservar", u"Crear reserva", None))
#if QT_CONFIG(tooltip)
        self.JTA_pushButton_reservar.setToolTip(QCoreApplication.translate("JTA_Reservar", u"<html><head/><body><p>Crear reserva</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.JTA_pushButton_reservar.setText(QCoreApplication.translate("JTA_Reservar", u"RESERVAR", None))
#if QT_CONFIG(tooltip)
        self.JTA_pushButton_actualizares.setToolTip(QCoreApplication.translate("JTA_Reservar", u"<html><head/><body><p>Modificar reserva</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.JTA_pushButton_actualizares.setText(QCoreApplication.translate("JTA_Reservar", u"ACTUALIZAR RESERVA", None))
        self.JTA_groupBox_datres.setTitle(QCoreApplication.translate("JTA_Reservar", u"Datos de la reserva", None))
        self.JTA_label_numpersonas.setText(QCoreApplication.translate("JTA_Reservar", u"N\u00ba Personas", None))
        self.JTA_label_fecha.setText(QCoreApplication.translate("JTA_Reservar", u"Fecha de reserva", None))
        self.JTA_checkBox_habnecesarias.setText("")
        self.JTA_label_tiporeserva.setText(QCoreApplication.translate("JTA_Reservar", u"Tipo reserva", None))
        self.JTA_label_habnecesarias.setText(QCoreApplication.translate("JTA_Reservar", u"\u00bfSe necesitan habitaciones?", None))
        self.JTA_label_tipococina.setText(QCoreApplication.translate("JTA_Reservar", u"Tipo de cocina", None))
        self.JTA_lineEdit_numpersonas.setText("")
        self.JTA_lineEdit_jornadas.setText("")
        self.JTA_label_jornadas.setText(QCoreApplication.translate("JTA_Reservar", u"N\u00ba Jornadas", None))
        self.JTA_groupBox_datcli.setTitle(QCoreApplication.translate("JTA_Reservar", u"Datos del cliente", None))
        self.JTA_label_nombre.setText(QCoreApplication.translate("JTA_Reservar", u"Nombre del cliente", None))
        self.JTA_lineEdit_telefono.setText("")
        self.JTA_lineEdit_nombre.setText("")
        self.JTA_label_telefono.setText(QCoreApplication.translate("JTA_Reservar", u"Tel\u00e9fono de contacto", None))
        self.JTA_label_resicon.setText("")
        self.JTA_label_title.setText(QCoreApplication.translate("JTA_Reservar", u"RESERVA", None))
        self.JTA_label_enc.setText("")
#if QT_CONFIG(tooltip)
        self.JTA_pushButton_volver.setToolTip(QCoreApplication.translate("JTA_Reservar", u"Volver al men\u00fa principal", None))
#endif // QT_CONFIG(tooltip)
        self.JTA_pushButton_volver.setText("")
    # retranslateUi

