# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: health.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0chealth.proto\x12\x06Health\x1a\x1bgoogle/protobuf/empty.proto\",\n\tHealthDto\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t2@\n\x06Health\x12\x36\n\tGetHealth\x12\x16.google.protobuf.Empty\x1a\x11.Health.HealthDtoB\r\xaa\x02\nFemtum.SDKb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'health_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\nFemtum.SDK'
  _globals['_HEALTHDTO']._serialized_start=53
  _globals['_HEALTHDTO']._serialized_end=97
  _globals['_HEALTH']._serialized_start=99
  _globals['_HEALTH']._serialized_end=163
# @@protoc_insertion_point(module_scope)
