from enum import Enum


class AuthenticationMethod12Code(Enum):
    APKI = "APKI"
    ADVF = "ADVF"
    ARNB = "ARNB"
    ARPC = "ARPC"
    ARQC = "ARQC"
    ATCC = "ATCC"
    BTHD = "BTHD"
    CHSA = "CHSA"
    CHDN = "CHDN"
    CUID = "CUID"
    DRVI = "DRVI"
    DRLN = "DRLN"
    EMAL = "EMAL"
    EMIN = "EMIN"
    EMRN = "EMRN"
    IDCN = "IDCN"
    MANU = "MANU"
    NVSC = "NVSC"
    FBIG = "FBIG"
    FBIO = "FBIO"
    OLDA = "OLDA"
    OLDS = "OLDS"
    OFPE = "OFPE"
    FCPN = "FCPN"
    OTPW = "OTPW"
    NBIG = "NBIG"
    NPIN = "NPIN"
    OCHI = "OCHI"
    OTHN = "OTHN"
    OTHP = "OTHP"
    PPSG = "PPSG"
    PSVE = "PSVE"
    PASN = "PASN"
    PSWD = "PSWD"
    TOKP = "TOKP"
    PKIS = "PKIS"
    PLOB = "PLOB"
    PCDV = "PCDV"
    SCRT = "SCRT"
    SCNL = "SCNL"
    CSEC = "CSEC"
    SHAF = "SHAF"
    SHAT = "SHAT"
    CPSG = "CPSG"
    SSNB = "SSNB"
    TXIN = "TXIN"
    TOKA = "TOKA"
    CDHI = "CDHI"
    TOKN = "TOKN"
    QWAC = "QWAC"
    PHOM = "PHOM"
    PWOR = "PWOR"
    THDS = "THDS"
    ADDB = "ADDB"
    ADDS = "ADDS"
    CSCV = "CSCV"
    CRYP = "CRYP"
    BIOM = "BIOM"
    MOBL = "MOBL"
    FPIN = "FPIN"
    NTID = "NTID"
    ACSN = "ACSN"
    CHSN = "CHSN"


class CardSecurityCapability1Code(Enum):
    ICCD = "ICCD"
    MWOS = "MWOS"
    MSWS = "MSWS"
    OTHN = "OTHN"
    OTHP = "OTHP"
    OLPN = "OLPN"
