from enum import Enum


class AddendumTaxType3Code(Enum):
    TOTL = "TOTL"
    ALMI = "ALMI"
    ASNT = "ASNT"
    BPTX = "BPTX"
    KAPA = "KAPA"
    NKAP = "NKAP"
    CRTX = "CRTX"
    CSTX = "CSTX"
    CITX = "CITX"
    COAX = "COAX"
    CPST = "CPST"
    CORT = "CORT"
    COTX = "COTX"
    CUST = "CUST"
    DLTX = "DLTX"
    DUTY = "DUTY"
    EMIT = "EMIT"
    EMUT = "EMUT"
    EMET = "EMET"
    EMST = "EMST"
    EMRT = "EMRT"
    ENTX = "ENTX"
    ESET = "ESET"
    ENVT = "ENVT"
    EQUL = "EQUL"
    EQTX = "EQTX"
    EUTR = "EUTR"
    EXEC = "EXEC"
    FEXT = "FEXT"
    FNST = "FNST"
    FETX = "FETX"
    FVAT = "FVAT"
    FVTS = "FVTS"
    FIMT = "FIMT"
    FSST = "FSST"
    FICA = "FICA"
    FRTX = "FRTX"
    FSTX = "FSTX"
    FSFT = "FSFT"
    FUVT = "FUVT"
    GIFT = "GIFT"
    GCAT = "GCAT"
    GRTX = "GRTX"
    HVAT = "HVAT"
    HATX = "HATX"
    HSTX = "HSTX"
    HWTX = "HWTX"
    INHT = "INHT"
    INPO = "INPO"
    LTTX = "LTTX"
    FLST = "FLST"
    LITX = "LITX"
    LOCO = "LOCO"
    LSTX = "LSTX"
    LOCL = "LOCL"
    LUTX = "LUTX"
    MATX = "MATX"
    METX = "METX"
    MITX = "MITX"
    MUTX = "MUTX"
    MUDE = "MUDE"
    COUN = "COUN"
    NATI = "NATI"
    OCTX = "OCTX"
    OPTX = "OPTX"
    OTHR = "OTHR"
    OTHN = "OTHN"
    OTHP = "OTHP"
    OTTX = "OTTX"
    LEVY = "LEVY"
    POTX = "POTX"
    PRTX = "PRTX"
    PSTX = "PSTX"
    PPTX = "PPTX"
    PROV = "PROV"
    PHET = "PHET"
    QUST = "QUST"
    ROCI = "ROCI"
    RCSB = "RCSB"
    RCSD = "RCSD"
    ROTX = "ROTX"
    RVAT = "RVAT"
    ROVI = "ROVI"
    SAUT = "SAUT"
    SCTX = "SCTX"
    SPTX = "SPTX"
    STTA = "STTA"
    STAM = "STAM"
    SLST = "SLST"
    SLTX = "SLTX"
    SETX = "SETX"
    STPT = "STPT"
    SPTS = "SPTS"
    SPFT = "SPFT"
    SPTG = "SPTG"
    SRTX = "SRTX"
    SSTX = "SSTX"
    STAT = "STAT"
    STSL = "STSL"
    STEX = "STEX"
    SUTX = "SUTX"
    CTAX = "CTAX"
    TDDT = "TDDT"
    TELT = "TELT"
    THTX = "THTX"
    TRAX = "TRAX"
    TRAN = "TRAN"
    UNSP = "UNSP"
    UUTX = "UUTX"
    VATA = "VATA"
    VATB = "VATB"
    WTAX = "WTAX"
    WESV = "WESV"
    WITF = "WITF"
    WITL = "WITL"
    WITH = "WITH"
    TNRT = "TNRT"
    DPTX = "DPTX"


class AttestationValue1Code(Enum):
    CLAI = "CLAI"
    HONO = "HONO"
    NCLA = "NCLA"
    NHON = "NHON"


class BalanceType15Code(Enum):
    AMOH = "AMOH"
    AMTO = "AMTO"
    AMTD = "AMTD"
    CRDL = "CRDL"
    OTHN = "OTHN"
    OTHP = "OTHP"
    AVLB = "AVLB"
    CLRI = "CLRI"
    LDGR = "LDGR"
    PNTS = "PNTS"


class CarRentalActivity1Code(Enum):
    CARS = "CARS"
    GLBL = "GLBL"
    INDV = "INDV"
    PETP = "PETP"
    OTHP = "OTHP"
    OTHN = "OTHN"
    OTHR = "OTHR"


class CarRentalServiceType2Code(Enum):
    ADJM = "ADJM"
    AUTH = "AUTH"
    BAST = "BAST"
    CLEA = "CLEA"
    DMGS = "DMGS"
    DLVR = "DLVR"
    DPOF = "DPOF"
    ENTE = "ENTE"
    EXTC = "EXTC"
    EXDY = "EXDY"
    EXDI = "EXDI"
    EXHR = "EXHR"
    FINE = "FINE"
    FUEL = "FUEL"
    GARA = "GARA"
    GPSY = "GPSY"
    INSU = "INSU"
    LATE = "LATE"
    LIIN = "LIIN"
    LDIN = "LDIN"
    MISC = "MISC"
    NAVI = "NAVI"
    NOSH = "NOSH"
    ONEW = "ONEW"
    OTHN = "OTHN"
    OTHP = "OTHP"
    PARK = "PARK"
    PRIN = "PRIN"
    PFIN = "PFIN"
    PHON = "PHON"
    REGD = "REGD"
    SMOK = "SMOK"
    TOLL = "TOLL"
    TOWI = "TOWI"


class CompanyAssigner2Code(Enum):
    ASSO = "ASSO"
    AUTH = "AUTH"
    CPNY = "CPNY"
    LEII = "LEII"
    TRAG = "TRAG"
    OTHP = "OTHP"
    OTHN = "OTHN"


class CustomerAssigner1Code(Enum):
    AUTH = "AUTH"
    CRCY = "CRCY"
    CUST = "CUST"
    ONFL = "ONFL"
    OTHR = "OTHR"
    TRAY = "TRAY"


class Exemption2Code(Enum):
    PKGE = "PKGE"
    TMBE = "TMBE"
    RECP = "RECP"
    LOWA = "LOWA"
    SCPE = "SCPE"
    TRAE = "TRAE"
    CTLS = "CTLS"
    PAAC = "PAAC"
    TRSP = "TRSP"


class FleetPurchaseType1Code(Enum):
    FUEL = "FUEL"
    NONF = "NONF"
    FANF = "FANF"


class FleetServiceType1Code(Enum):
    SLSV = "SLSV"
    HSDI = "HSDI"
    FLSV = "FLSV"


class JourneyType1Code(Enum):
    COAC = "COAC"
    EARL = "EARL"
    FLGT = "FLGT"
    LATE = "LATE"
    ONTM = "ONTM"
    OTHR = "OTHR"
    TRAN = "TRAN"
    VESS = "VESS"


class LegalStructure1Code(Enum):
    STAE = "STAE"
    PVIN = "PVIN"
    MUNI = "MUNI"
    CNTY = "CNTY"
    NATI = "NATI"


class LocationAmenity1Code(Enum):
    AADA = "AADA"
    AFLA = "AFLA"
    AVLA = "AVLA"
    CRWA = "CRWA"
    CVSA = "CVSA"
    DISA = "DISA"
    EWAA = "EWAA"
    MRLA = "MRLA"
    OTHN = "OTHN"
    OTHP = "OTHP"
    PAPA = "PAPA"
    TSHA = "TSHA"
    TSRA = "TSRA"
    TSSA = "TSSA"
    TFHA = "TFHA"
    VSWA = "VSWA"
    VHPA = "VHPA"
    VMRA = "VMRA"


class LodgingActivity1Code(Enum):
    APTM = "APTM"
    BEBR = "BEBR"
    COTT = "COTT"
    CRUI = "CRUI"
    HOME = "HOME"
    HOST = "HOST"
    HOTL = "HOTL"
    LODG = "LODG"
    MOTL = "MOTL"
    OTHN = "OTHN"
    OTHP = "OTHP"
    RESO = "RESO"
    ROAB = "ROAB"
    TOSH = "TOSH"


class LodgingService1Code(Enum):
    ACCO = "ACCO"
    AUDI = "AUDI"
    BANQ = "BANQ"
    BREK = "BREK"
    BUSS = "BUSS"
    CONC = "CONC"
    EARA = "EARA"
    EARD = "EARD"
    ENTR = "ENTR"
    FCAA = "FCAA"
    GAME = "GAME"
    GARA = "GARA"
    GIFT = "GIFT"
    HEAL = "HEAL"
    INTE = "INTE"
    LAUN = "LAUN"
    LONG = "LONG"
    MINI = "MINI"
    NOSH = "NOSH"
    OTHR = "OTHR"
    PARK = "PARK"
    PHON = "PHON"
    REST = "REST"
    RMSE = "RMSE"
    SPAS = "SPAS"
    THRD = "THRD"
    TRAN = "TRAN"
    VODS = "VODS"


class LoyaltyValueType1Code(Enum):
    MILE = "MILE"
    MONE = "MONE"
    OTHR = "OTHR"
    POIN = "POIN"
    PRIV = "PRIV"


class OfficialDocumentType1Code(Enum):
    ARNU = "ARNU"
    AUTH = "AUTH"
    DIPL = "DIPL"
    DVLC = "DVLC"
    EURO = "EURO"
    IDEN = "IDEN"
    INTE = "INTE"
    INPO = "INPO"
    LZPR = "LZPR"
    OTHN = "OTHN"
    OTHP = "OTHP"
    PASS = "PASS"
    VISA = "VISA"
    PERM = "PERM"
    REFU = "REFU"


class PeriodUnit2Code(Enum):
    HOUR = "HOUR"
    HFDA = "HFDA"
    DAYS = "DAYS"
    WEEK = "WEEK"
    MNTH = "MNTH"
    YEAR = "YEAR"
    MINU = "MINU"
    OTHR = "OTHR"


class PeriodUnit3Code(Enum):
    OTHP = "OTHP"
    OTHN = "OTHN"
    MNTH = "MNTH"
    WEEK = "WEEK"
    YEAR = "YEAR"
    DAYS = "DAYS"
    EXDY = "EXDY"


class PeriodUnit4Code(Enum):
    OTHP = "OTHP"
    OTHN = "OTHN"
    MNTH = "MNTH"
    WEEK = "WEEK"
    YEAR = "YEAR"
    DAYS = "DAYS"
    EXDY = "EXDY"
    MINU = "MINU"
    HFDA = "HFDA"
    HOUR = "HOUR"
    OTHR = "OTHR"


class PresentationMedium2Code(Enum):
    BIOM = "BIOM"
    ELEC = "ELEC"
    PAPR = "PAPR"
    BOTH = "BOTH"


class ProductCodeType1Code(Enum):
    EA13 = "EA13"
    EAN8 = "EAN8"
    GTIN = "GTIN"
    OTHR = "OTHR"
    PLUP = "PLUP"
    RS14 = "RS14"
    UPCA = "UPCA"
    UPCE = "UPCE"


class TaxReclaimMethod1Code(Enum):
    INPP = "INPP"
    INPS = "INPS"
    INSU = "INSU"
    OTHR = "OTHR"


class TelephonyCallType1Code(Enum):
    VCML = "VCML"
    TFPC = "TFPC"
    PAGE = "PAGE"
    OGPC = "OGPC"
    OTHP = "OTHP"
    OTHN = "OTHN"
    OTCL = "OTCL"
    ICPC = "ICPC"


class TemporaryServicesCharge1Code(Enum):
    WKND = "WKND"
    REGL = "REGL"
    OVRT = "OVRT"
    OTHP = "OTHP"
    OTHN = "OTHN"
    ONCL = "ONCL"
    NITE = "NITE"
    HOLI = "HOLI"
    HAZD = "HAZD"


class TimeSegment1Code(Enum):
    AMBN = "AMBN"
    PMAN = "PMAN"


class TransportType1Code(Enum):
    AIRR = "AIRR"
    BUSS = "BUSS"
    OTHN = "OTHN"
    OTHP = "OTHP"
    RAIL = "RAIL"
    SHIP = "SHIP"


class TypeOfAmount19Code(Enum):
    CONN = "CONN"
    INSU = "INSU"
    LNDS = "LNDS"
    MISC = "MISC"
    OTHN = "OTHN"
    OTHP = "OTHP"
    USGE = "USGE"


class TypeTypeOfAmount23Code(Enum):
    AMTH = "AMTH"
    BAGG = "BAGG"
    CARG = "CARG"
    CHTC = "CHTC"
    CLUB = "CLUB"
    DUTY = "DUTY"
    EXTK = "EXTK"
    EXTF = "EXTF"
    EXTR = "EXTR"
    FARE = "FARE"
    FDBV = "FDBV"
    INSU = "INSU"
    MISC = "MISC"
    OTHN = "OTHN"
    OTHP = "OTHP"
    PETC = "PETC"
    PHNE = "PHNE"
    PRPY = "PRPY"
    TOTL = "TOTL"
    TOUR = "TOUR"
    UPGD = "UPGD"
    TKDL = "TKDL"
    FEES = "FEES"


class UnitOfMeasure10Code(Enum):
    KMET = "KMET"
    MILE = "MILE"
