"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing

try:
    import yandex.cloud.priv.iam.v1.access_binding_service_pb2
except ImportError:
    import datasphere.yandex.cloud.priv.iam.v1.access_binding_service_pb2


try:
    import yandex.cloud.priv.servicecontrol.v1.resource_pb2
except ImportError:
    import datasphere.yandex.cloud.priv.servicecontrol.v1.resource_pb2


DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ListSubjectAccessBindingsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUBJECT_ID_FIELD_NUMBER: builtins.int
    INCLUDE_ALL_USERS_FIELD_NUMBER: builtins.int
    INCLUDE_ALL_AUTHENTICATED_USERS_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    subject_id: builtins.str
    include_all_users: builtins.bool
    include_all_authenticated_users: builtins.bool
    page_size: builtins.int
    page_token: builtins.str
    def __init__(
        self,
        *,
        subject_id: builtins.str = ...,
        include_all_users: builtins.bool = ...,
        include_all_authenticated_users: builtins.bool = ...,
        page_size: builtins.int = ...,
        page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["include_all_authenticated_users", b"include_all_authenticated_users", "include_all_users", b"include_all_users", "page_size", b"page_size", "page_token", b"page_token", "subject_id", b"subject_id"]) -> None: ...

global___ListSubjectAccessBindingsRequest = ListSubjectAccessBindingsRequest

@typing.final
class ListSubjectAccessBindingsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCESS_BINDINGS_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    next_page_token: builtins.str
    @property
    def access_bindings(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SubjectAccessBinding]: ...
    def __init__(
        self,
        *,
        access_bindings: collections.abc.Iterable[global___SubjectAccessBinding] | None = ...,
        next_page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["access_bindings", b"access_bindings", "next_page_token", b"next_page_token"]) -> None: ...

global___ListSubjectAccessBindingsResponse = ListSubjectAccessBindingsResponse

@typing.final
class ListHistoryRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCE_ID_FIELD_NUMBER: builtins.int
    RESOURCE_TYPE_FIELD_NUMBER: builtins.int
    SUBJECT_ID_FIELD_NUMBER: builtins.int
    MODIFIED_AT_SINCE_FIELD_NUMBER: builtins.int
    MODIFIED_AT_UNTIL_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    resource_id: builtins.str
    resource_type: builtins.str
    subject_id: builtins.str
    page_size: builtins.int
    page_token: builtins.str
    @property
    def modified_at_since(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def modified_at_until(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        resource_id: builtins.str = ...,
        resource_type: builtins.str = ...,
        subject_id: builtins.str = ...,
        modified_at_since: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        modified_at_until: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        page_size: builtins.int = ...,
        page_token: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["modified_at_since", b"modified_at_since", "modified_at_until", b"modified_at_until"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["modified_at_since", b"modified_at_since", "modified_at_until", b"modified_at_until", "page_size", b"page_size", "page_token", b"page_token", "resource_id", b"resource_id", "resource_type", b"resource_type", "subject_id", b"subject_id"]) -> None: ...

global___ListHistoryRequest = ListHistoryRequest

@typing.final
class ListHistoryResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCESS_BINDING_HISTORY_ENTRIES_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    next_page_token: builtins.str
    @property
    def access_binding_history_entries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___AccessBindingHistoryEntry]: ...
    def __init__(
        self,
        *,
        access_binding_history_entries: collections.abc.Iterable[global___AccessBindingHistoryEntry] | None = ...,
        next_page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["access_binding_history_entries", b"access_binding_history_entries", "next_page_token", b"next_page_token"]) -> None: ...

global___ListHistoryResponse = ListHistoryResponse

@typing.final
class AccessBindingHistoryEntry(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    ROLE_ID_FIELD_NUMBER: builtins.int
    SUBJECT_FIELD_NUMBER: builtins.int
    MODIFIED_AT_FIELD_NUMBER: builtins.int
    DELETED_AT_FIELD_NUMBER: builtins.int
    IS_SYSTEM_FIELD_NUMBER: builtins.int
    MODIFIED_BY_FIELD_NUMBER: builtins.int
    RESOURCE_FIELD_NUMBER: builtins.int
    TOP_LEVEL_RESOURCE_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    id: builtins.str
    role_id: builtins.str
    is_system: builtins.bool
    modified_by: builtins.str
    @property
    def subject(self) -> yandex.cloud.priv.iam.v1.access_binding_service_pb2.Subject: ...
    @property
    def modified_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def deleted_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def resource(self) -> yandex.cloud.priv.servicecontrol.v1.resource_pb2.Resource: ...
    @property
    def top_level_resource(self) -> yandex.cloud.priv.servicecontrol.v1.resource_pb2.Resource: ...
    @property
    def metadata(self) -> global___IamControlPlaneHistoryMetadata: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        role_id: builtins.str = ...,
        subject: yandex.cloud.priv.iam.v1.access_binding_service_pb2.Subject | None = ...,
        modified_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        deleted_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        is_system: builtins.bool = ...,
        modified_by: builtins.str = ...,
        resource: yandex.cloud.priv.servicecontrol.v1.resource_pb2.Resource | None = ...,
        top_level_resource: yandex.cloud.priv.servicecontrol.v1.resource_pb2.Resource | None = ...,
        metadata: global___IamControlPlaneHistoryMetadata | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["deleted_at", b"deleted_at", "metadata", b"metadata", "modified_at", b"modified_at", "resource", b"resource", "subject", b"subject", "top_level_resource", b"top_level_resource"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["deleted_at", b"deleted_at", "id", b"id", "is_system", b"is_system", "metadata", b"metadata", "modified_at", b"modified_at", "modified_by", b"modified_by", "resource", b"resource", "role_id", b"role_id", "subject", b"subject", "top_level_resource", b"top_level_resource"]) -> None: ...

global___AccessBindingHistoryEntry = AccessBindingHistoryEntry

@typing.final
class SubjectAccessBinding(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ROLE_ID_FIELD_NUMBER: builtins.int
    RESOURCE_FIELD_NUMBER: builtins.int
    SUBJECT_FIELD_NUMBER: builtins.int
    IS_SYSTEM_FIELD_NUMBER: builtins.int
    role_id: builtins.str
    is_system: builtins.bool
    @property
    def resource(self) -> yandex.cloud.priv.servicecontrol.v1.resource_pb2.Resource: ...
    @property
    def subject(self) -> yandex.cloud.priv.iam.v1.access_binding_service_pb2.Subject: ...
    def __init__(
        self,
        *,
        role_id: builtins.str = ...,
        resource: yandex.cloud.priv.servicecontrol.v1.resource_pb2.Resource | None = ...,
        subject: yandex.cloud.priv.iam.v1.access_binding_service_pb2.Subject | None = ...,
        is_system: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["resource", b"resource", "subject", b"subject"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["is_system", b"is_system", "resource", b"resource", "role_id", b"role_id", "subject", b"subject"]) -> None: ...

global___SubjectAccessBinding = SubjectAccessBinding

@typing.final
class IamControlPlaneHistoryMetadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUBJECT_ID_FIELD_NUMBER: builtins.int
    ON_BEHALF_OF_SUBJECT_ID_FIELD_NUMBER: builtins.int
    REQUEST_ID_FIELD_NUMBER: builtins.int
    TX_ID_FIELD_NUMBER: builtins.int
    subject_id: builtins.str
    on_behalf_of_subject_id: builtins.str
    request_id: builtins.str
    tx_id: builtins.str
    def __init__(
        self,
        *,
        subject_id: builtins.str = ...,
        on_behalf_of_subject_id: builtins.str = ...,
        request_id: builtins.str = ...,
        tx_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["on_behalf_of_subject_id", b"on_behalf_of_subject_id", "request_id", b"request_id", "subject_id", b"subject_id", "tx_id", b"tx_id"]) -> None: ...

global___IamControlPlaneHistoryMetadata = IamControlPlaneHistoryMetadata
