"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
import typing

try:
    import yandex.cloud.priv.iam.v1.backoffice.permission_service_pb2
except ImportError:
    import datasphere.yandex.cloud.priv.iam.v1.backoffice.permission_service_pb2


_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class PermissionServiceStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    Check: grpc.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.backoffice.permission_service_pb2.CheckPermissionRequest,
        yandex.cloud.priv.iam.v1.backoffice.permission_service_pb2.CheckPermissionResponse,
    ]

class PermissionServiceAsyncStub:
    Check: grpc.aio.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.backoffice.permission_service_pb2.CheckPermissionRequest,
        yandex.cloud.priv.iam.v1.backoffice.permission_service_pb2.CheckPermissionResponse,
    ]

class PermissionServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Check(
        self,
        request: yandex.cloud.priv.iam.v1.backoffice.permission_service_pb2.CheckPermissionRequest,
        context: _ServicerContext,
    ) -> typing.Union[yandex.cloud.priv.iam.v1.backoffice.permission_service_pb2.CheckPermissionResponse, collections.abc.Awaitable[yandex.cloud.priv.iam.v1.backoffice.permission_service_pb2.CheckPermissionResponse]]: ...

def add_PermissionServiceServicer_to_server(servicer: PermissionServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
