
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-16T20:05:41-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "ea877227c11968158d91e1ccd601bfceeca8bde2",
 "version": "3.1.13.dev6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
