from enum import Enum


class RejectedStatusReason12Code(Enum):
    BLCA = "BLCA"
    DOCC = "DOCC"
    IAQD = "IAQD"
    ICTN = "ICTN"
    CYPA = "CYPA"
    TREF = "TREF"
    DSEC = "DSEC"
    IDNA = "IDNA"
    DQUA = "DQUA"
    FTAX = "FTAX"
    INID = "INID"
    INAC = "INAC"
    CASH = "CASH"
    INPM = "INPM"
    INNA = "INNA"
    SAFE = "SAFE"
    INUK = "INUK"
    LEGL = "LEGL"
    NSLA = "NSLA"
    SECU = "SECU"
    PTNS = "PTNS"
    DLVY = "DLVY"
    DDAT = "DDAT"
    ISTP = "ISTP"
    DEPT = "DEPT"
    ISAT = "ISAT"
    OTHR = "OTHR"
    NCON = "NCON"
    ACLO = "ACLO"
    NASS = "NASS"
    NQTY = "NQTY"
    BLTR = "BLTR"
    COSE = "COSE"
    ILLI = "ILLI"
    BMRV = "BMRV"
    DINV = "DINV"
    ICAG = "ICAG"
    IPAC = "IPAC"
    INTE = "INTE"
    DMON = "DMON"
    PRCT = "PRCT"
    IVAG = "IVAG"
    NCRR = "NCRR"
    DTRD = "DTRD"
    UPAY = "UPAY"
    URSC = "URSC"


class TypeOfRequest1Code(Enum):
    INFO = "INFO"
    STAT = "STAT"
