# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/priv/datasphere/v2/ssa_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1yandex/cloud/priv/datasphere/v2/ssa_service.proto\x12\x1fyandex.cloud.priv.datasphere.v2\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"c\n\x18GetServiceAccountRequest\x12\x33\n\x04type\x18\x01 \x01(\x0e\x32%.yandex.cloud.priv.datasphere.v2.Type\x12\x12\n\nproject_id\x18\x02 \x01(\t\"\x8a\x01\n\x19GetServiceAccountResponse\x12\x33\n\x04type\x18\x01 \x01(\x0e\x32%.yandex.cloud.priv.datasphere.v2.Type\x12\x17\n\x0fservice_account\x18\x02 \x01(\t\x12\x10\n\x08\x63loud_id\x18\x03 \x01(\t\x12\r\n\x05\x65mpty\x18\x04 \x01(\x08*:\n\x04Type\x12\x14\n\x10TYPE_UNSPECIFIED\x10\x00\x12\x1c\n\x18NOTEBOOK_SERVICE_ACCOUNT\x10\x01\x32\x99\x01\n\nSsaService\x12\x8a\x01\n\x11GetServiceAccount\x12\x39.yandex.cloud.priv.datasphere.v2.GetServiceAccountRequest\x1a:.yandex.cloud.priv.datasphere.v2.GetServiceAccountResponseB6\n\"yandex.cloud.priv.datasphere.v2ydsB\x04SSASZ\ndatasphereb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yandex.cloud.priv.datasphere.v2.ssa_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\"yandex.cloud.priv.datasphere.v2ydsB\004SSASZ\ndatasphere'
  _globals['_TYPE']._serialized_start=425
  _globals['_TYPE']._serialized_end=483
  _globals['_GETSERVICEACCOUNTREQUEST']._serialized_start=183
  _globals['_GETSERVICEACCOUNTREQUEST']._serialized_end=282
  _globals['_GETSERVICEACCOUNTRESPONSE']._serialized_start=285
  _globals['_GETSERVICEACCOUNTRESPONSE']._serialized_end=423
  _globals['_SSASERVICE']._serialized_start=486
  _globals['_SSASERVICE']._serialized_end=639
# @@protoc_insertion_point(module_scope)
