USER_AGENT = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
VENDOR = "Intel Inc."
RENDERER = "Intel Iris OpenGL Engine"
WEBSITE_AVG_LOAD_TIME = 6
# Average loading time for slowest websites: https://speedmonitor.io/topsites
SLOWEST_WEBSITE_AVG_LOAD_TIME = 14

DEFAULT_QUERY_ELEMENTS_TIMEOUT_SECONDS = 300
DEFAULT_QUERY_DATA_TIMEOUT_SECONDS = 900
DEFAULT_QUERY_GENERATE_TIMEOUT_SECONDS = 75
DEFAULT_PAGINATION_CLICK_TIMEOUT_MS = 5000
DEFAULT_PAGINATION_CLICK_FORCE = False
DEFAULT_WAIT_FOR_NETWORK_IDLE = True
DEFAULT_INCLUDE_HIDDEN_DATA = True
DEFAULT_INCLUDE_HIDDEN_ELEMENTS = False
CURRENT_TF_ID_ATTR = "current_tf_id"
