"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
import typing

try:
    import yandex.cloud.priv.iam.v1.transitional.roles_service_pb2
except ImportError:
    import datasphere.yandex.cloud.priv.iam.v1.transitional.roles_service_pb2


_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class RoleServiceStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    List: grpc.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.transitional.roles_service_pb2.ListRolesRequest,
        yandex.cloud.priv.iam.v1.transitional.roles_service_pb2.ListRolesResponse,
    ]

class RoleServiceAsyncStub:
    List: grpc.aio.UnaryUnaryMultiCallable[
        yandex.cloud.priv.iam.v1.transitional.roles_service_pb2.ListRolesRequest,
        yandex.cloud.priv.iam.v1.transitional.roles_service_pb2.ListRolesResponse,
    ]

class RoleServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def List(
        self,
        request: yandex.cloud.priv.iam.v1.transitional.roles_service_pb2.ListRolesRequest,
        context: _ServicerContext,
    ) -> typing.Union[yandex.cloud.priv.iam.v1.transitional.roles_service_pb2.ListRolesResponse, collections.abc.Awaitable[yandex.cloud.priv.iam.v1.transitional.roles_service_pb2.ListRolesResponse]]: ...

def add_RoleServiceServicer_to_server(servicer: RoleServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
