from enum import Enum


class NonEquityAssetClass1Code(Enum):
    SDRV = "SDRV"
    IRDV = "IRDV"
    FEXD = "FEXD"
    EQDV = "EQDV"
    EADV = "EADV"
    EMAL = "EMAL"
    CRDV = "CRDV"
    CFDS = "CFDS"
    COMD = "COMD"
    C10_D = "C10D"
    BOND = "BOND"
    ETCS = "ETCS"
    ETNS = "ETNS"
    SFPS = "SFPS"


class NonEquitySubClassSegmentationCriteria1Code(Enum):
    ASCL = "ASCL"
    BSPD = "BSPD"
    CNC1 = "CNC1"
    CNC2 = "CNC2"
    NCCO = "NCCO"
    CTYP = "CTYP"
    NCCR = "NCCR"
    DCSL = "DCSL"
    DTYP = "DTYP"
    EQUT = "EQUT"
    FNC1 = "FNC1"
    FNC2 = "FNC2"
    FSPD = "FSPD"
    IIND = "IIND"
    IRTC = "IRTC"
    INC1 = "INC1"
    INC2 = "INC2"
    ISIN = "ISIN"
    TTMO = "TTMO"
    PRMT = "PRMT"
    SSRF = "SSRF"
    ISPT = "ISPT"
    SRTC = "SRTC"
    SACL = "SACL"
    SBPD = "SBPD"
    TTMS = "TTMS"
    NCSW = "NCSW"
    TTMB = "TTMB"
    IOUB = "IOUB"
    TOUB = "TOUB"
    UISC = "UISC"
    UIDX = "UIDX"
    UINS = "UINS"
    UIRT = "UIRT"
    REOU = "REOU"
    UTYP = "UTYP"
