
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-16T22:22:52+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "70041d613b6a1065fe2897c292afa1bb18a0aec0",
 "version": "1.90.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
