from enum import Enum


class SystemEventType2Code(Enum):
    LVCO = "LVCO"
    LVCC = "LVCC"
    LVRT = "LVRT"
    EUSU = "EUSU"
    STSU = "STSU"
    LWSU = "LWSU"
    EUCO = "EUCO"
    FIRE = "FIRE"
    STDY = "STDY"
    LTNC = "LTNC"
    CRCO = "CRCO"
    RECC = "RECC"
    LTGC = "LTGC"
    LTDC = "LTDC"
    CUSC = "CUSC"
    IBKC = "IBKC"
    SYSC = "SYSC"
    SSSC = "SSSC"
    REOP = "REOP"
    PCOT = "PCOT"
    NPCT = "NPCT"
    ESTF = "ESTF"
