from typing_extensions import TypeAlias

_Bytes: TypeAlias = bytes

def standard_b64encode(s: _Bytes) -> _Bytes: ...
def urlsafe_b64encode(s: _Bytes) -> _Bytes: ...
def standard_b64decode(s: _Bytes) -> _Bytes: ...
def urlsafe_b64decode(s: _Bytes) -> _Bytes: ...
