
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-15T08:51:03+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "480906244f27b27c34e140e6ca7be0573b707a01",
 "version": "2.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
