"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class AdminProjectInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class RoomInfo(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        class _Status:
            ValueType = typing.NewType("ValueType", builtins.int)
            V: typing_extensions.TypeAlias = ValueType

        class _StatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[AdminProjectInfo.RoomInfo._Status.ValueType], builtins.type):
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
            STATUS_UNDEFINED: AdminProjectInfo.RoomInfo._Status.ValueType  # 0
            PREPARING: AdminProjectInfo.RoomInfo._Status.ValueType  # 1
            READY: AdminProjectInfo.RoomInfo._Status.ValueType  # 2
            CHECKOUT: AdminProjectInfo.RoomInfo._Status.ValueType  # 3
            ARCHIVING: AdminProjectInfo.RoomInfo._Status.ValueType  # 4
            RESIZING: AdminProjectInfo.RoomInfo._Status.ValueType  # 5
            STOPPED_IDE: AdminProjectInfo.RoomInfo._Status.ValueType  # 6
            STARTING_IDE: AdminProjectInfo.RoomInfo._Status.ValueType  # 7
            CHECK_IN_ERROR: AdminProjectInfo.RoomInfo._Status.ValueType  # 8

        class Status(_Status, metaclass=_StatusEnumTypeWrapper): ...
        STATUS_UNDEFINED: AdminProjectInfo.RoomInfo.Status.ValueType  # 0
        PREPARING: AdminProjectInfo.RoomInfo.Status.ValueType  # 1
        READY: AdminProjectInfo.RoomInfo.Status.ValueType  # 2
        CHECKOUT: AdminProjectInfo.RoomInfo.Status.ValueType  # 3
        ARCHIVING: AdminProjectInfo.RoomInfo.Status.ValueType  # 4
        RESIZING: AdminProjectInfo.RoomInfo.Status.ValueType  # 5
        STOPPED_IDE: AdminProjectInfo.RoomInfo.Status.ValueType  # 6
        STARTING_IDE: AdminProjectInfo.RoomInfo.Status.ValueType  # 7
        CHECK_IN_ERROR: AdminProjectInfo.RoomInfo.Status.ValueType  # 8

        STATUS_FIELD_NUMBER: builtins.int
        INSTANCE_ID_FIELD_NUMBER: builtins.int
        IPV6_FIELD_NUMBER: builtins.int
        status: global___AdminProjectInfo.RoomInfo.Status.ValueType
        instance_id: builtins.str
        ipv6: builtins.str
        def __init__(
            self,
            *,
            status: global___AdminProjectInfo.RoomInfo.Status.ValueType = ...,
            instance_id: builtins.str = ...,
            ipv6: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["instance_id", b"instance_id", "ipv6", b"ipv6", "status", b"status"]) -> None: ...

    @typing.final
    class Worker(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        INSTANCE_ID_FIELD_NUMBER: builtins.int
        instance_id: builtins.str
        def __init__(
            self,
            *,
            instance_id: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["instance_id", b"instance_id"]) -> None: ...

    PROJECT_ID_FIELD_NUMBER: builtins.int
    ROOM_FIELD_NUMBER: builtins.int
    WORKERS_FIELD_NUMBER: builtins.int
    IDE_FIELD_NUMBER: builtins.int
    JOB_WORKERS_FIELD_NUMBER: builtins.int
    project_id: builtins.str
    @property
    def room(self) -> global___AdminProjectInfo.RoomInfo: ...
    @property
    def workers(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___AdminProjectInfo.Worker]: ...
    @property
    def ide(self) -> global___AdminProjectInfo.Worker: ...
    @property
    def job_workers(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___AdminProjectInfo.Worker]: ...
    def __init__(
        self,
        *,
        project_id: builtins.str = ...,
        room: global___AdminProjectInfo.RoomInfo | None = ...,
        workers: collections.abc.Iterable[global___AdminProjectInfo.Worker] | None = ...,
        ide: global___AdminProjectInfo.Worker | None = ...,
        job_workers: collections.abc.Iterable[global___AdminProjectInfo.Worker] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["ide", b"ide", "room", b"room"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["ide", b"ide", "job_workers", b"job_workers", "project_id", b"project_id", "room", b"room", "workers", b"workers"]) -> None: ...

global___AdminProjectInfo = AdminProjectInfo
