"""
This type stub file was generated by pyright.
"""

from typing import Generic, TYPE_CHECKING, TypeVar
from graph_sitter.core.expressions.union_type import UnionType
from graph_sitter.writer_decorators import py_apidoc

if TYPE_CHECKING:
    ...
Parent = TypeVar("Parent")
@py_apidoc
class PyUnionType(UnionType["PyType", Parent], Generic[Parent]):
    """Union type

    Examples:
        str | int
    """
    ...


