from enum import Enum


class CancelledStatusReason17Code(Enum):
    CANI = "CANI"
    OTHR = "OTHR"
    CSUB = "CSUB"
    CANS = "CANS"


class PendingReason17Code(Enum):
    CONF = "CONF"


class RejectionReason62Code(Enum):
    REFE = "REFE"
    ADEA = "ADEA"
    CCIX = "CCIX"
    CCTI = "CCTI"
    IIND = "IIND"
    PTYA = "PTYA"
    PTYB = "PTYB"
    ITPA = "ITPA"
    LATE = "LATE"
    SAFA = "SAFA"
    SAFB = "SAFB"
    REDT = "REDT"
    SEPR = "SEPR"
    LBDR = "LBDR"
    DCBR = "DCBR"
    CSAC = "CSAC"
    TERM = "TERM"
    DTRD = "DTRD"
    DDAT = "DDAT"
    NCRR = "NCRR"
    IESP = "IESP"
    IEXT = "IEXT"
    IPBI = "IPBI"
    IRIT = "IRIT"
    TMAC = "TMAC"
    REPA = "REPA"
    TXAC = "TXAC"
    NRGM = "NRGM"
    TABC = "TABC"
    ICTT = "ICTT"
    NRJN = "NRJN"
    NFCA = "NFCA"
    CTRA = "CTRA"


class RejectionReason63Code(Enum):
    REFE = "REFE"
    ADEA = "ADEA"
    CCIX = "CCIX"
    CCTI = "CCTI"
    IIND = "IIND"
    PTYA = "PTYA"
    PTYB = "PTYB"
    LATE = "LATE"
    ITPA = "ITPA"
    SAFA = "SAFA"
    SAFB = "SAFB"
    REDT = "REDT"
    DCAN = "DCAN"
    DPRG = "DPRG"
    RSET = "RSET"
    RREP = "RREP"
    NRJN = "NRJN"


class UnmatchedReason15Code(Enum):
    CPCA = "CPCA"
    DCBS = "DCBS"
    TMOP = "TMOP"
    OPTP = "OPTP"
    OFRF = "OFRF"
    SPRD = "SPRD"
    RITP = "RITP"
    RATE = "RATE"
    TMCY = "TMCY"
    TXCY = "TXCY"
    TXAM = "TXAM"
    MNTP = "MNTP"
    EGSP = "EGSP"
    EXPO = "EXPO"
    DTRD = "DTRD"
    REDT = "REDT"
    CMIS = "CMIS"
    TFRT = "TFRT"
    TERM = "TERM"
    INPD = "INPD"
    PYFQ = "PYFQ"
    CSAC = "CSAC"
    LBKD = "LBKD"
    CRYD = "CRYD"
    TENO = "TENO"
    SEPR = "SEPR"
