"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from codegen.utils.codemod.codemod_writer_decorators import py_apidoc
from graph_sitter.core.statements.statement import Statement

if TYPE_CHECKING:
    ...
@py_apidoc
class PyPassStatement(Statement["PyCodeBlock"]):
    """An abstract representation of a python pass statement."""
    statement_type = ...


