from enum import Enum


class ExoticOptionStyle1Code(Enum):
    BINA = "BINA"
    DIGI = "DIGI"
    NOTO = "NOTO"
    VANI = "VANI"


class Frequency11Code(Enum):
    YEAR = "YEAR"
    DAIL = "DAIL"
    MNTH = "MNTH"
    EXPI = "EXPI"
    OVNG = "OVNG"
    QURT = "QURT"
    MIAN = "MIAN"
    UPFR = "UPFR"
    WEEK = "WEEK"
    CRED = "CRED"


class OptionEventType1Code(Enum):
    CLST = "CLST"
    CONF = "CONF"
    KNIN = "KNIN"
    KNOC = "KNOC"
    OTHR = "OTHR"
    TRIG = "TRIG"


class OptionStyle5Code(Enum):
    AMER = "AMER"
    ASIA = "ASIA"
    BERM = "BERM"
    EURO = "EURO"


class UnitOfMeasure8Code(Enum):
    KILO = "KILO"
    KMET = "KMET"
    KWDC = "KWDC"
    KWHO = "KWHO"
    KWHC = "KWHC"
    KMOC = "KMOC"
    KWMC = "KWMC"
    KWYC = "KWYC"
    LITR = "LITR"
    MWDC = "MWDC"
    MWHO = "MWHO"
    MWHC = "MWHC"
    MWMC = "MWMC"
    MMOC = "MMOC"
    MWYC = "MWYC"
    METR = "METR"
    TONE = "TONE"
    MILE = "MILE"
    MILI = "MILI"
    MMET = "MMET"
    MIBA = "MIBA"
    MBTU = "MBTU"
    PIEC = "PIEC"
    PUND = "PUND"
    PWRD = "PWRD"
    SHAS = "SHAS"
    SCMT = "SCMT"
    SQFO = "SQFO"
    SQIN = "SQIN"
    SQKI = "SQKI"
    SMET = "SMET"
    SQMI = "SQMI"
    SMIL = "SMIL"
    SQYA = "SQYA"
    THMS = "THMS"
    TONS = "TONS"
    TOCD = "TOCD"
    OZTR = "OZTR"
    USGA = "USGA"
    UCWT = "UCWT"
    USOU = "USOU"
    USPI = "USPI"
    USQA = "USQA"
    YARD = "YARD"
    ACRE = "ACRE"
    ALOW = "ALOW"
    ACCY = "ACCY"
    ARES = "ARES"
    BARL = "BARL"
    BCUF = "BCUF"
    BDFT = "BDFT"
    BUSL = "BUSL"
    CELI = "CELI"
    CMET = "CMET"
    CEER = "CEER"
    CLRT = "CLRT"
    CBME = "CBME"
    DAYS = "DAYS"
    DGEU = "DGEU"
    DMET = "DMET"
    ENVC = "ENVC"
    ENVO = "ENVO"
    FOOT = "FOOT"
    GGEU = "GGEU"
    GBGA = "GBGA"
    GBOU = "GBOU"
    GBPI = "GBPI"
    GBQA = "GBQA"
    GRAM = "GRAM"
    HECT = "HECT"
    HUWG = "HUWG"
    INCH = "INCH"
    IPNT = "IPNT"
    FUTU = "FUTU"
    USTN = "USTN"
