"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING, TypeVar
from codegen.utils.codemod.codemod_writer_decorators import ts_apidoc
from graph_sitter.core.expressions.named_type import NamedType

if TYPE_CHECKING:
    ...
Parent = TypeVar("Parent")
@ts_apidoc
class TSNamedType(NamedType[Parent]):
    """Named type
    Examples:
        string
    """
    ...


