"""Predefined units."""

def define_units() -> None: ...
def define_base_si_units() -> None: ...
def define_complex_si_units() -> None: ...
def define_time_units() -> None: ...
def define_volumes() -> None: ...
def define_imperial_units() -> None: ...
def define_astronomical_units() -> None: ...
def define_computer_units() -> None: ...
def define_ridiculous_units() -> None: ...
