from enum import Enum


class ActionType(str, Enum):
    LOGIN = "LOGIN"
    GET_X_USER = "GET_X_USER"
    FOLLOW = "FOLLOW"
    UNFOLLOW = "UNFOLLOW"
    FOLLOWERS = "FOLLOWERS"
    VERIFIED_FOLLOWERS = "VERIFIED_FOLLOWERS"
    FOLLOWING = "FOLLOWING"
    USER_TWEETS = "USER_TWEETS"
    USER_TWEETS_AND_REPLIES = "USER_TWEETS_AND_REPLIES"
    READ_DMS = "READ_DMS"
    SEND_DM = "SEND_DM"
    REPLY_XEET = "REPLY_XEET"
    NOTIFICATIONS = "NOTIFICATIONS"
    HOME_TIMELINE = "HOME_TIMELINE"
    SEARCH = "SEARCH"
    LIKE = "LIKE"
